### ISSUE TITLE
Missing/incorrect image key for black dragon fireball

### ISSUE THREAD

**Issue by sams-joseph** [odota/ui#1001]
https://www.opendota.com/matches/3214900214/combat (see Chen damage dealt)

**Comment by howardchung** [comment]
In addition to adding the key to dotaconstants, looks like we actually have to find and put an image in this directory:

https://github.com/odota/ui/tree/master/assets/images/dota2/neutral_abilities

**Comment by snugghash** [comment]
Is the 6th image (TEMPEST) supposed to be the same as `enraged_windkin_tornado`? That's broken as well, but asset exists.

**Comment by snugghash** [comment]
I'd like to report that a grep reveals that this exists:
    ./dotaconstants/build/abilities.json:27599:    "dname": "Fireball",
    ./dotaconstants/build/abilities.json-27600-    "behavior": [
    ./dotaconstants/build/abilities.json-27601-      "Point Target",
    ./dotaconstants/build/abilities.json-27602-      "AOE"
    --
    ./dotaconstants/build/abilities.json-27628-    ],
    ./dotaconstants/build/abilities.json-27629-    "mc": "100",
    ./dotaconstants/build/abilities.json-27630-    "cd": "10",
    ./dotaconstants/build/abilities.json:27631:    "img": "/apps/dota2/images/abilities/black_dragon_fireball_md.png"
    ./dotaconstants/build/abilities.json-27632-  },

How does this relate?

**Comment by snugghash** [comment]
Finally, any tests to be done before I submit a PR to both repos?

**Comment by howardchung** [comment]
The original fix was to rename the tornado_tempest key name to point at the right image.  We could have renamed the image too, but we didn't do that.

It's possible that Valve just changed the ability key name, in which case it might be more correct to list both keys in the file and point at the same image.

The `img` path in that file is constructed based on the ability name.  It works well for most hero abilities, but Valve doesn't store images for non-hero abilities at the same path, see http://cdn.dota2.com/apps/dota2/images/abilities/black_dragon_fireball_md.png

**Comment by howardchung** [comment]
If CI passes on odota/ui, you're good.  You can run the UI locally to verify the issue is fixed as well.
