### ISSUE TITLE
Wrong numbers on 'vision'

### ISSUE THREAD

**Issue by justmeeee** [odota/ui#1009]
https://www.opendota.com/matches/3233518989/vision

'Dire vision' says Nyx bought 15 and placed 4 observers, but if you look on 'ward log' it shows 11 wards.

**Comment by howardchung** [comment]
This is the same issue as:
https://github.com/odota/ui/issues/975

Basically the new(-ish) ward_dispenser item is messing up the item use counts, so we should use the log instead.
