### ISSUE TITLE
Expose Public Match Data checked but matches not appearing on OpenDota? Matches appear on Dotabuff

### ISSUE THREAD

**Issue by jacobs61695** [odota/ui#1010]

**Comment by howardchung** [comment]
There was some Steam API unavailability earlier today that led to delays in matches showing up.  Looks like the issues have been fixed, so we should be caught up.

Are there still missing matches?

**Comment by howardchung** [comment]
please reopen/comment if there are further issues.  Siltbreaker means heavier load on the API which means higher likelihood of Steam API issues.
