### ISSUE TITLE
[Suggestion] Better to add tower tier in Story modea

### ISSUE THREAD

**Issue by leovarmak** [odota/ui#1016]
I really loved this story mode. So I was reading my story and then realised I was so much into it. Then when Meepo destroyed one of the towers I had trouble visualising it as to which tower it was.

So its better if its mentioned which tower was destroyed and which lane it belonged to. Attaching a screenshot to better explain myself

![image](https://user-images.githubusercontent.com/14135553/27166689-1c2f67b2-51ba-11e7-9803-8ff5043b1d74.png)

**Comment by howardchung** [comment]
@mdiller 

Unfortunately I think the data doesn't have the tower that was destroyed.

This is the same issue as #816

**Comment by howardchung** [comment]
If we manage to figure out a way to get the data we'll definitely do this though!

**Comment by leovarmak** [comment]
@howardchung Sorry. I forgot to look at open issues. Cool
