### ISSUE TITLE
swapping tabs back and forth removes filtering from table

### ISSUE THREAD

**Issue by mike-robertson** [odota/ui#102]
example: put 10k matches limit filter on overview. Then swap to heroes tab. then go back to overview. Your filter will be gone because the page makes a request for the regular data amount which overrides the data. This causes a bug with pagination where you are stuck on a page which no longer exists, but the pagination controls don't render since that page is empty.

**Comment by mike-robertson** [comment]
resolved by #101

**Comment by howardchung** [comment]
@mike-robertson is this fixed?

**Comment by mike-robertson** [comment]
Yea the bug should have been named differently, but what I described is no longer happening.
