### ISSUE TITLE
Error when trying to request a parse

### ISSUE THREAD

**Issue by denis331** [odota/ui#1026]
Hello!

I am trying to request a parse on OpenDota but it says "Failed to get match data" .

These are the matches I am trying to request a parse for:
2657449493
2917955705

Can anyone help me? The replays are very important to me ! :pray: 

Thank you!

**Comment by howardchung** [comment]
Unfortunately, Valve only keeps replays for 10 days (3 months for battle pass owners), if the match is not a ticketed/pro match.
