### ISSUE TITLE
Show abandoned indicator on player summary

### ISSUE THREAD

**Issue by nastyez** [odota/ui#1033]
Why does no stats recorded count as loss, please fix it. By the way i realy like opendota more than dotabuff.

**Comment by howardchung** [comment]
Do you have a link to the match in question?

**Comment by nastyez** [comment]
No, i dont think that would help, im just noticing that in dota 2 recent matches where is shown that no stats are recorded turns to count as loss in opendota.

**Comment by howardchung** [comment]
Yeah but with the link I can check the data to see why they're showing up like that

**Comment by nastyez** [comment]
Never mind looks like i was wrong sorry. But i noticed only that 1 game that i abandoned was shown to be loss instead abandon (i know its the same thing but still it would be great if i knew that that was the game i abandoned).

**Comment by howardchung** [comment]
I'll need the match ID/link to the match in order to debug the issue.

**Comment by nastyez** [comment]
Sure https://www.opendota.com/matches/3267009755

**Comment by howardchung** [comment]
According to the API, stats were recorded for this game.  Does it show up otherwise on your Dota (in-game) profile?

**Comment by howardchung** [comment]
To clarify, on the match page it will show if a player abandoned or not.  However, on a player page it will just show the result of the player's team (win or loss), even if the player abandoned.  If you want it to show the abandoned indcator on the player summary as well, I guess that's a feature request that we could consider.

**Comment by aarmora** [comment]
I'd be interested in adding this. Current I don't show that the player object returned from the API for the match has any indication of whether it was an abandon or not. Am I missing something? Would an abandoned flag need to be added to the matches returned from the API?

**Comment by howardchung** [comment]
Yeah, we have to project the leaver_status column into the queries for both the /recentMatches and /matches endpoint.  Should be a quick fix but requires a change to odota/core.

**Comment by howardchung** [comment]
/matches can be fixed by adding onto the project parameter:
https://api.opendota.com/api/players/88367253/matches?project=leaver_status&limit=10

**Comment by aarmora** [comment]
Gulp. That means I better figure out docker.

Why not just include the leaver status in all of the match objects instead of using a query param? Excuse me if this would be more clear if I understood the project better.

**Comment by howardchung** [comment]
That's an option as well, just need to add leaver_status as a default field that always shows up.

If you're having issues getting odota/core running I can make these changes pretty quickly myself.

**Comment by aarmora** [comment]
Yeah, I can't get odota/core up yet. I hope to be able to put more time in today to get docker up going.

**Comment by howardchung** [comment]
I made the change in:
https://github.com/odota/core/commit/ec0ff11405c644ec2e237c9e444ac1c03a29650b

If you want to work on this you can just work on adding it to the UI.

**Comment by aarmora** [comment]
@howardchung Trying to find it in the UI now. Thanks!
