### ISSUE TITLE
MMR delays

### ISSUE THREAD

**Issue by dotabug** [odota/ui#1036]
https://www.opendota.com/players/154715080
In this example, at 8:07 PM June 26 2016, this player's MMR is 9999 Dbuff its already 10024. 
[Opendota](https://a.safe.moe/XhUgS.png) 
[Dotabuff](https://a.safe.moe/HhHm2.png)

**Comment by howardchung** [comment]
Unfortunately the MMR fetching is kind of unreliable and it can return different values depending on a variety of factors, such as how long after the match the data is requested.  Requesting too quickly leads to the data not being updated.

We could manually refresh this player's data, but this may still happen from time to time.

**Comment by howardchung** [comment]
I manually forced an update.  For reference this is the Redis command I used:
`redis-cli lpush mmrQueue "{\"account_id\": 154715080, \"match_id\": 3274457422}"`

**Comment by nabuqodonosori** [comment]
My MMR is refreshed 11.08.2016. Please do something or tell me how to fix.

**Comment by howardchung** [comment]
See the response in https://github.com/odota/ui/issues/1052
