### ISSUE TITLE
make filter arrow disabled instead of disappearing

### ISSUE THREAD

**Issue by howardchung** [odota/ui#104]
Currently on the first and last page, the arrow for the end won't render at all.  This causes the entire page list to shift, which can confuse the user.

**Comment by mike-robertson** [comment]
It's an easy change, but are you sure disabled is preferable to disappeared? I'll make the change and we can play around with that.

**Comment by howardchung** [comment]
Mainly, I think we should just avoid the shift that causes the number to jump around.  If you want it to disappear but keep its spacing so the numbers don't move, that's fine also
