### ISSUE TITLE
Siltbreaker matches are being included in the player profile overview Averages/Maximums in last 20 matches

### ISSUE THREAD

**Issue by awailes** [odota/ui#1040]
When I go to my Player Profile, and am on the Overview tab, the calculations for the Averages/Maximums in last 20 matches is including  Event / Co-Op Bots matches from siltbreaker (the custom game).  These matches are labeled as Event / Co-Op Bots matches.  These are not real Dota matches and should not be included in the calculations for the Averages/Maximums in last 20 matches.  I have attached a picture that shows the issue.

![bug](https://user-images.githubusercontent.com/29739702/27608784-b3cd8a4a-5b56-11e7-81cf-f40125388bde.png)

**Comment by blukai** [comment]
https://github.com/odota/core/issues/1474

**Comment by howardchung** [comment]
Yeah, although I think it makes more sense to filter these matches from the calculation on the client side, so I'll close the core issue in favor of this one.
