### ISSUE TITLE
Error thrown when viewing Story

### ISSUE THREAD

**Issue by gu3st** [odota/ui#1042]
With game: https://www.opendota.com/matches/3280538799/story

I get exception: `Cannot read property 'key' of undefined | stack: TypeError: Cannot read property 'key' of undefined
    at re (https://www.opendota.com/build/bundle.js:56:341737)
    at t.value (https://www.opendota.com/build/bundle.js:56:343303)
    at t.value (https://www.opendota.com/build/bundle.js:56:343501)`

I think it's the truthiness check here.  https://github.com/odota/ui/blob/master/src/components/Match/MatchStory.jsx#L579

killerLog will always evaluate to true, even if it's an empty array.  Should check that killerLog is an instanceof an array, THEN check for the 0th index and whether or not it's an object.

I'd make the change myself, but I'm so unfamiliar with the codebase at this point that I'm worried about breaking other stuff.

**Comment by howardchung** [comment]
@mdiller 

If you think you can make the change, go ahead and submit a PR!  We'll check it out during code review

**Comment by mdiller** [comment]
Oops. Didn't mean to close this. Yeah sounds like that fix will do it!
