### ISSUE TITLE
How many match entries odota stores?

### ISSUE THREAD

**Issue by valeriilos** [odota/ui#1054]
Tried to get a thousand or so for my little project, but seems that I can get only 100 with  https://api.opendota.com/api/publicMatches
and when I add
?less_than_match_id=[oldestIDIGot]
it returns nothing 
and if I request with ?less_than_match_id=[mostRecentIDIGot]
it returns less than 100 results. 
How do I get more than this? If it's not a problem, please store more entries.

**Comment by howardchung** [comment]
Are you sure you passed the oldest ID (smallest number?).  Can you provide a sample link?

**Comment by valeriilos** [comment]
https://api.opendota.com/api/publicMatches returns a list where
responce[0]['match_id'] = 3283084804
responce[99]['match_id'] = 3283089507

https://api.opendota.com/api/publicMatches?less_than_match_id=3283084804
returns this '[]'

I've already kind of solved my issue, I request latest 100 matches every 100 seconds and it gives me different matches all the time. In case of matchId repeating I check if I've already saved that match. 
This method is relatively slow, but I've already managed to download 10 000 matches.

**Comment by howardchung** [comment]
I added an order by that should fix the issue (matches should be sorted in descending match ID order).

**Comment by howardchung** [comment]
See https://github.com/odota/core/issues/1490 for continuation
