### ISSUE TITLE
Chat emoticons

### ISSUE THREAD

**Issue by blukai** [odota/ui#1056]
Display dota emoticons in chat messages on `matches/match_id/chat`.
One day I'll do it, or someone else 😛

**Comment by howardchung** [comment]
example?

**Comment by gu3st** [comment]
http://dota2.gamepedia.com/Emoticons

For instance, :bc_100: will map to 💯 .  There's some other ones that map to more DOTA centric ones (like : thinking : will become an ember spirit thinking (instead of the default 🤔 )

**Comment by blukai** [comment]
[Match](https://www.opendota.com/matches/3170212000/chat)

![image](https://user-images.githubusercontent.com/20866892/27842448-de8d0a8c-6112-11e7-941c-039e2b6a7008.png)

Dota 2 [emoticons in vdf](https://github.com/SteamDatabase/GameTracking-Dota2/blob/master/game/dota/pak01_dir/scripts/emoticons.txt
) (can be easily converted to json)

Zerostartingpoint 😛  is `0xE000`, it can be converted to char here [link](https://r12a.github.io/apps/conversion/), since it hosted on github, we can peep, how conversion is done.

For example `:wink:` <img src="https://hydra-media.cursecdn.com/dota2.gamepedia.com/6/65/Emoticon_wink.gif?version=2254c49d4aee69984d1329693facab80" align="right"> is `0xE001` - ``

**Comment by mdiller** [comment]
So would we be wanting to get the [images from the vpk](https://github.com/SteamDatabase/GameTracking-Dota2/tree/master/game/dota/pak01_dir/resource/flash3/images/emoticons) and convert them all into gifs and store them in the assets folder then?

**Comment by blukai** [comment]
Unfortunately not all icons can be found on page, that @mdiller provided. File `pak01_dir.vpk` located in `Steam\SteamApps\common\dota 2 beta\game\dota` contains all icons in `panorama\images`.
