### ISSUE TITLE
Story: Net Worth difference at x minutes in

### ISSUE THREAD

**Issue by TrentBartlem** [odota/ui#1065]
The story shows a heading every 10 minutes. It would be nice to show the net worth difference at each checkpoint, e.g:

<img width="476" alt="screen shot 2017-07-12 at 2 07 31 pm" src="https://user-images.githubusercontent.com/171650/28101386-839827fc-670b-11e7-9c23-ae9ead78a020.png">

or something similar.

Or if not in the header, as a line item directly below it.

**Comment by howardchung** [comment]
Sounds like a good idea!  @mdiller

**Comment by mdiller** [comment]
Yeah cool idea. I'll see what I can do!

**Comment by mdiller** [comment]
I was thinking maybe something like this. (with text added for details)
![networth_mockup](https://user-images.githubusercontent.com/3231343/28193392-31f64c30-67f1-11e7-8545-0c9a96cab669.png)
Any thoughts?
