### ISSUE TITLE
"Stone Form" spell icon is throwing a 404 Error

### ISSUE THREAD

**Issue by KaLam1tyAC** [odota/ui#1068]
Specifically calls to URL: https://api.opendota.com/apps/dota2/images/abilities/visage_summon_familiars_stone_form_lg.png

Screenshot: https://cdn.discordapp.com/attachments/197560147529170944/336068808764555274/unknown.png

**Comment by KaLam1tyAC** [comment]
Wiki Image (128px): https://hydra-media.cursecdn.com/dota2.gamepedia.com/2/20/Stone_Form_%28Familiar%29_icon.png?version=867aa08d6e52a1727695c59bf674a5a8

**Comment by souravmondal93** [comment]
@howardchung 
I tried to fix this error, but I found that the [dotaconstants](https://github.com/odota/dotaconstants) repository has some issue with the image file, it is not pointing to correct file location. I also searched dotabuff for a similar image, but I was not able to find it, as they haven't used this image file anywhere.

**Comment by howardchung** [comment]
You need to put the image in:
https://github.com/odota/ui/tree/master/assets/images/dota2/neutral_abilities

And add it to the neutral_abilities.json in dotaconstants

**Comment by howardchung** [comment]
It's the easiest fix.  It's just named that because originally this issue only affected neutral abilities.

**Comment by souravmondal93** [comment]
Okay. I will update the code in both the repositories and I will send the PRs. :)
