### ISSUE TITLE
Order of rows changes on Networth/XP table

### ISSUE THREAD

**Issue by mdiller** [odota/ui#1078]
This is the table you get on hover for the graphs of networth and XP. Seems like they should be consistent.
![image](https://user-images.githubusercontent.com/3231343/28496031-2be7762c-6f15-11e7-937b-fa87aaa04086.png)
![image](https://user-images.githubusercontent.com/3231343/28496033-3f64c916-6f15-11e7-9f42-b7d52340848a.png)

**Comment by howardchung** [comment]
I think this is due to the sorting logic used on the tooltip for the gold/xp/lh graphs.  Should probably disable for this graph.
