### ISSUE TITLE
Data Explorer

### ISSUE THREAD

**Issue by howardchung** [odota/ui#108]
- [x] allow free SQL querying of competitive/pro matches
- [x] graphical query builder
~store recent queries in local storage history~
- [x] json download button

**Comment by dartharaknus** [comment]
How about using lucene syntax which is the industry standard for these kind of things?

**Comment by howardchung** [comment]
I've never tried using that before, but wouldn't we need to translate the input into SQL (since the data is stored in Postgres?)

**Comment by dartharaknus** [comment]
Depends. We need research on this.

**Comment by howardchung** [comment]
This is a prerelease feature and the SQL querying is implemented:
http://beta.opendota.com/explorer

There are also a couple of users using the API directly (submitting SQL via the API).

I'd like to build out an easier-to-use form based interface (so users don't have to know SQL or look up hero_id etc.), before releasing this officially.
