### ISSUE TITLE
AM's stuns count with negative seconds

### ISSUE THREAD

**Issue by Buldy** [odota/ui#1084]
I think there is a problem with AM's mana void counting negative seconds to stuns.

![bez nazvu](https://user-images.githubusercontent.com/16001712/28725014-61ebb0ca-73bc-11e7-9b84-e23c0c7581ec.png)

**Comment by howardchung** [comment]
Yeah, I don't know why this happens but we don't compute this field ourselves, it's read out of the replay file so it is a probably a bug for Valve to fix.
