### ISSUE TITLE
Match not processed at all

### ISSUE THREAD

**Issue by lanster99** [odota/ui#1087]
Match in question: https://www.opendota.com/matches/3344000233

Shows up on profile as no hero, 48 years ago etc.

**Comment by howardchung** [comment]
Looks fine now?

**Comment by lanster99** [comment]
I used request a parse on the match id and it fixed it.  Not sure what caused it in the first place though.

**Comment by howardchung** [comment]
Did you just enable public match data?

**Comment by lanster99** [comment]
Nope, haven't touched any of my dota settings.  The match I played yesterday was processed fine, and the ones I played after it today where processed fine.  Just seems that the match data never got processed (processed as in the stage before parsing), but it had the match listed with the match id on my profile.

**Comment by howardchung** [comment]
Hmm, if you see it again don't request a parse and let me know, I'll try to investigate the issue
