### ISSUE TITLE
MMR tracking not working at all

### ISSUE THREAD

**Issue by drusepth** [odota/ui#1093]
Hi, I'm looking at [this URL](https://www.opendota.com/players/84783156/mmr) where I have a single MMR data point (from 2015), even though [I've played many, many ranked matches since then](https://www.opendota.com/players/84783156/matches?lobby_type=7). My current MMR (1,225 currently) is also off from the displayed MMR on Opendota (1,182, which I haven't been for some time).

Is this a bug, or am I just not triggering matches to be recorded/tracked in some way?

Screenshot of MMR graph:
![mmr](https://user-images.githubusercontent.com/538235/28756246-03fd30b4-756b-11e7-98ec-9f427ac8df55.png)

**Comment by howardchung** [comment]
Did you do this?

https://blog.opendota.com/2016/01/13/yasp-mmr-and-you/

**Comment by drusepth** [comment]
Oh, I definitely didn't -- didn't know about it. 

Enabled it and played a game and it seems to be working now. Is there any way to retrieve historical data?

Thank!
