### ISSUE TITLE
incomplete user table

### ISSUE THREAD

**Issue by alexey-formalmethods** [odota/ui#1096]
Hi!
select * from players
where profileurl='http://steamcommunity.com/profiles/76561198158859091/'
limit 100

It's my account, why does sql return 0 rows?

**Comment by howardchung** [comment]
You need to use account_id:
https://www.opendota.com/explorer?sql=select%20*%20from%20players%0D%0Awhere%20account_id%20%3D%2088367253&format=

**Comment by alexey-formalmethods** [comment]
So why can i find someone else by profileurl, but am not able to query my own account?

**Comment by howardchung** [comment]
There could be a variety of reasons, it depends on whether they are present in the database.  We discover players when they play matches with public match data turned on, or log in, so it's not 100% complete.

Also, there is no index on profileurl so querying on that will be very slow.

**Comment by alexey-formalmethods** [comment]
Yes, my profile public match data is turned off, now it's clear. Thank you!
