### ISSUE TITLE
Match data does not auto parse even if logged in using Steam

### ISSUE THREAD

**Issue by Aw3som3n3zz** [odota/ui#1100]

**Comment by howardchung** [comment]
Yes, automatic parsing is somewhat unreliable lately due to Valve rate limiting accessing to replay salts.  Hopefully this will improve after TI is over.  For now, you may have to request parsing for matches that you want parsed more quickly.

**Comment by howardchung** [comment]
It looks like the limits have been lifted so automatic parsing should resume.
