### ISSUE TITLE
A match cannot be parsed.

### ISSUE THREAD

**Issue by XuZhilei** [odota/ui#1110]
sry for my poor English
https://www.opendota.com/matches/3370054178
I tried to parse this match, however after I clicked submit button, there only raised "The replay for this match has not yet been parsed. Not all data may be available." and nothing would be parsed. But this issue can only be found on this match, while other matches are regular. I tried several IP address to submit, but the same issue raised.

**Comment by XuZhilei** [comment]
It seems like Valve's missing the replays for this match.
http://replay111.valve.net/570/3370054178_1346084491.dem.bz2
Sad.

**Comment by howardchung** [comment]
Yeah, unfortunately Valve loses replays from time to time (even for big events like TI)
