### ISSUE TITLE
1v1 mid replays almost never load once parsed

### ISSUE THREAD

**Issue by g3rezz** [odota/ui#1113]
1v1 mid replays almost never load once parsed. Unparsed replays for the most part can be viewed.
That was not the case a couple of months ago ( maybe 4 months ago).
I don't know if it has something to do with valve removing the download feature for 1v1 replays in the game client. Sometimes , very rarely though, parsed 1v1 replays do load and can be downloaded from opendota. I am aware that the replay needs to be 5 minutes or longer in order to be downloadable.
Example: https://www.opendota.com/matches/3372136535

**Comment by howardchung** [comment]
Looks like a JavaScript crash in the UI.  Investigating

**Comment by g3rezz** [comment]
Thank you very much for fixing the issue so promptly. I am now able to load all my 1 vs 1 games and download them. I wasn't expecting anybody to care about this mode. Thanks again, you guys are doing a great work with the site!
