### ISSUE TITLE
Show link to instructions for enabling MMR updates

### ISSUE THREAD

**Issue by Rabid5** [odota/ui#1121]
![graph for bug report]
![graph for bug report](https://user-images.githubusercontent.com/31115124/29438192-0c20c3c0-8383-11e7-992b-3abbcaf256bb.PNG)

**Comment by howardchung** [comment]
Did you follow the directions here?

https://blog.opendota.com/2016/01/13/yasp-mmr-and-you/

**Comment by blukai** [comment]
@howardchung I regularly see problems with updating the MMR, perhaps we should add text that explains how it works on the MMR page?

**Comment by howardchung** [comment]
Yeah, that's probably a good idea

**Comment by CauchyAbel** [comment]
@blukai Waiting on your idea of how to implement it. The original post has been fixed to show OpenDota, mmr, and you

**Comment by blukai** [comment]
@CauchyAbel in `src/components/Alerts` u can fing `Warning`, u can create`Info` component by copying warning and replacing icon, color. I guess add link to the blogpost that explains how it works whould be enough. 🤔

**Comment by CauchyAbel** [comment]
@blukai Which one is better?

![](https://cdn.discordapp.com/attachments/197560147529170944/351576027702624267/unknown.png)

![](https://cdn.discordapp.com/attachments/197560147529170944/351576327884636160/unknown.png)

**Comment by blukai** [comment]
@CauchyAbel Maybe it's better to put it under the heading above graph? 🦄
