### ISSUE TITLE
Hero rankings bug

### ISSUE THREAD

**Issue by Neitqq** [odota/ui#1124]
If reporting a bug, the following information would be helpful:
- **Win 8.1**:
- **1366x768**:
- **Opera last ver.**:
- **https://www.opendota.com/players/93786490/rankings**:
- http://imgur.com/a/O9nYB:
My hero rankings is empty, but i was sure i saw my rankings one or two weeks ago

**Comment by howardchung** [comment]
I reset the rankings a while ago, and they now only show up if the user's score on a hero is greater than some threshold.  Keep playing and eventually it should show up
