### ISSUE TITLE
Sum of time dead in performance tab

### ISSUE THREAD

**Issue by kryonik** [odota/ui#1125]
Not really a bug per se but in the performance section, the summation of a team's total "time dead" is displayed as the total number of seconds dead. I feel like it would make more sense if it was in MM:SS format.
![opendota](https://user-images.githubusercontent.com/31144109/29478469-0edc3d34-843b-11e7-8027-45f163bdddcd.png)

**Comment by howardchung** [comment]
fixed in #1129
