### ISSUE TITLE
Stun time values should be rounded (Player profile/Trends/Stuns)

### ISSUE THREAD

**Issue by Doyle3694** [odota/ui#1126]
Example:
![image](https://user-images.githubusercontent.com/2184532/29482281-d0915cae-848e-11e7-995e-e73e382a709d.png)
Currently shows way more digits than can be deemed significant

Should be rounded like, for example, kills:
![image](https://user-images.githubusercontent.com/2184532/29482325-8f3a6236-848f-11e7-95cb-efc9930e8906.png)

**Comment by howardchung** [comment]
Think we just need to do `.toFixed(2)` on it.
