### ISSUE TITLE
Ability Build view

### ISSUE THREAD

**Issue by Xanvial** [odota/ui#1131]
Hi
There's a bug when viewing ability build on mobile, I can't view all levels after pressing triple dots button. Only last few level is visible.
OS: Android
Browser: Opera ver. 42.9
Resolution: 1080 x 1920 using portrait view

Suggestion, maybe move the ability build on different table on Overview tab. My experience is I need a while to found where to view it because the placement isn't noticeable

**Comment by howardchung** [comment]
@blukai do you think we should split it off into a table?  I agree it's probably better to have it visible without requiring a user interaction.

**Comment by blukai** [comment]
I think we can do it

**Comment by jhonnold** [comment]
Working on putting this in its own table - did we still want it on the overview page or on its own tab now?

**Comment by howardchung** [comment]
fixed in #1135
