### ISSUE TITLE
Why is my MMR not shown in my profile?

### ISSUE THREAD

**Issue by justmeeee** [odota/ui#1134]
Shouldn't the real MMR be shown in any profile where available? 
But all I see is the calculated MMR number.

**Comment by howardchung** [comment]
Did you follow the instructions here?

https://blog.opendota.com/2016/01/13/yasp-mmr-and-you/

**Comment by justmeeee** [comment]
Okay, I thought that it may be the cause but then I thought that any information should be available when I share my dota profile.

Thanks.
