### ISSUE TITLE
performance issue on match overview tab

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1136]
Switching to "overview" from any tab has a noticeable delay.  We should profile the components being rendered and see which ones are taking the longest, and possibly reduce the number of elements/move them to different tabs.

**Comment by howardchung** [comment]
As a quick check I did the following on a match overview:
```
document.getElementsByTagName('*').length
3963
```

I checked some other tabs and couldn't find a value over 1000.

Also, it appears that tooltips are not getting unloaded from the DOM.  You can verify this by mousing over a bunch of tooltips and then checking the number of nodes with the above command.

**Comment by howardchung** [comment]
I did a quick check on graphs tab and also got over 4000, so it seems like the c3 graphs are very DOM node heavy.  Perhaps we could build a more efficient visualization of gold/xp over time for the overview tab?

(and perhaps think about switching out c3 for a more efficient library)

**Comment by farmasek** [comment]
I have pretty good experience with [Recharts](http://recharts.org/#/en-US) as a graph library.

**Comment by howardchung** [comment]
Do you want to play with it and maybe switch a graph over to use it for a demo?

**Comment by farmasek** [comment]
ye sure, i will look into it and overall into this performance issue.

**Comment by howardchung** [comment]
I think this will be fixed with migration to recharts, let's roll this into #540
