### ISSUE TITLE
Chat doesn't load on certain match

### ISSUE THREAD

**Issue by bippum** [odota/ui#1137]
Error in console: https://dota.is-bad.com/83e3e8.png

- **OS**: Windows 10
- **Screen Resolution**: 1920x1080
- **Browser/Version**: Chrome 60.0.3112.101 (Official Build) (64-bit)
- **Link to page with the issue**: https://www.opendota.com/matches/3407034079/chat
- **Screenshot**: n/a

**Comment by howardchung** [comment]
@blukai might be an edge case not handled by the new chat UI
