### ISSUE TITLE
hero pages

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1143]
Improve the hero pages (currently we only display rankings and benchmarks).

Things we might want to add:
* Best against/worst against heroes
* Recent (pro?) matches with this hero
* graphs for winrate against time

**Comment by Luchanso** [comment]
I can try to do this, but where take data for it?

**Comment by howardchung** [comment]
The endpoints need to be implemented on odota/core.  You can check the table schema and test SQL queries using the Explorer.

I can also help with this, but I'll probably be implementing the team endpoints first.

**Comment by howardchung** [comment]
Proposed API endpoints to add:
/heroes/{heroId}/matchups: returns games played and wins against all other heroes (for pro matches)
/heroes/{heroId}/matches: return most recent games played with this hero
/heroes/{heroId}/durations: return games played and wins for each bucket of 5 minutes

**Comment by howardchung** [comment]
see this PR for an example:
https://github.com/odota/core/pull/1539

I might do this tomorrow if I have some time

**Comment by howardchung** [comment]
Endpoints implemented in:
https://github.com/odota/core/pull/1542
