### ISSUE TITLE
"undefinedth" hero ranking on Rankings tab

### ISSUE THREAD

**Issue by NiQDeveloper** [odota/ui#1155]
**Given** I am an odota user
**When** I visit the Rankings tab
**And** I have heroes returned
**Then** The rank column comes through as "undefinedth"
![image](https://user-images.githubusercontent.com/8285074/30234133-b0921db6-953d-11e7-8f24-ba1fc77cd4c3.png)

**Comment by howardchung** [comment]
I actually removed this column in https://github.com/odota/ui/commit/fe245f4c0761989d2f4e8a34c237ddfc7bed5315 but haven't deployed yet.  Will probably do this weekend
