### ISSUE TITLE
As a user, I should be able to filter out heroes with low matches played while reviewing hero performance.

### ISSUE THREAD

**Issue by wanderrful** [odota/ui#1157]
When filtering my heroes played for ranked matches only, for example, I want to sort by winrate but there are too many heroes for which I have fewer than 5 games played.  I should be able to check a box or enable a filter to remove heroes for which I have fewer than some number of games played (e.g. 5, 10, 15).

**Comment by howardchung** [comment]
hmm, maybe we could enable this as a client side filter and make it a common component usable for any table

**Comment by howardchung** [comment]
Implementing as a server side filter as an option as well, but takes a bit more work.  The advantage is that we can use the existing TableFilterForm component and just add a field.

**Comment by zaquille-oneil** [comment]
anyone working on this? I could try working on a sliding filter for games played

**Comment by howardchung** [comment]
There was some discussion about whether the filter should be implemented server side (then on the UI side we'd just add another field to the existing TableFilterForm)

**Comment by howardchung** [comment]
Which way did you want to implement it (client or server side?)

**Comment by zaquille-oneil** [comment]
If we do it on the front end, it can be componentized and reused elsewhere. Not sure how the backend works though. Will we need a new end point to determine how many games were played when on the Heroes page?

**Comment by howardchung** [comment]
The endpoint already returns the number of matches played on each hero.  However, there is currently no query parameter to filter the returned data based on a minimum number of matches played:

https://api.opendota.com/api/players/88367253/heroes

**Comment by dchasepdx** [comment]
Hey @zaquille-oneil, are you still working on this one? I've been thinking about a solution. Maybe we could collaborate on it.

**Comment by zaquille-oneil** [comment]
I haven't started. Let's collab

**Comment by wanderrful** [comment]
While trying to make progress with this -- I look at the other filters referencing a "data" variable... but I don't know where that data variable is defined.  Because of that. I can't figure out where the actual logic for applying the filter is supposed to go.

**Comment by howardchung** [comment]
which code?

**Comment by wanderrful** [comment]
@howardchung I forked the project, made a branch for the feature request and added this commit to highlight where I'm at:  https://github.com/wanderrful/ui/commit/b7636339a057fd61ba0d54b69118b45090ae0bf9

I included details in the commit description at the top of the page.

**Comment by howardchung** [comment]
The code you've edited is the displayFn.  This just determines how the column renders the current row into a table cell.

Since you want to filter on the rows of the table, you need to edit the Table component:
https://github.com/odota/ui/blob/master/src/components/Table/Table.jsx#L133

(see the existing code for how the Table handles sorts and pagination)

**Comment by wanderrful** [comment]
I have an example implementation of the filter placed here in this commit (I reverted the change made in that second link from earlier):  https://github.com/wanderrful/ui/commit/7b316eb8398c580dba30585349d5af1607756239

I only need to find out the proper way to get that filter value now and then I think we have a working feature.
