### ISSUE TITLE
incorrect time in story

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1164]
reported via reddit:
https://www.reddit.com/r/DotA2/comments/6zj5g2/i_really_like_opendotas_attention_to_detail_but/?st=j7h4ne1g&sh=45bb6810

attn @drusepth

**Comment by dchasepdx** [comment]
Hey,

I took a look at this one. It seems that for any match between 75 and 120 minutes it will return 'almost an hour'. I've got a quick fix that I'll make a pr for. It just changes 75 to 120 in the code below. 
```
else if (timeMinutes > 60 && timeMinutes <= 75) {
    // If the time is an hour to a quarter after, describe it as "over an hour"
    return `${strings.advb_over} ${strings.time_h}`;
  }
```
