### ISSUE TITLE
Outdated match records

### ISSUE THREAD

**Issue by sikspoyntpayb** [odota/ui#1176]
![image](https://user-images.githubusercontent.com/31998716/30498718-4ebdd556-9a8a-11e7-9764-6464fbe51f87.png)

**Comment by howardchung** [comment]
Could you describe in more detail what part is outdated?

**Comment by blukai** [comment]
@howardchung I think it's matches xd
@sikspoyntpayb If so, you need to expose public match data in dota 2 settings and then click refresh button in your opendota profile

**Comment by howardchung** [comment]
I'll assume that's the issue, please comment/reopen if it's not
