### ISSUE TITLE
no data for some players

### ISSUE THREAD

**Issue by LordVersA** [odota/ui#1179]
you dont have any data for some players like my profile :https://www.opendota.com/players/106757682

i press refresh alot and i login to steam but it still empty for me and my friends

**Comment by n1085113** [comment]
Have you enabled the in-game setting to share your match data?

Inside the game client, go to setting > Options tab > Advanced Options.
There, under the Social category, tick the "Expose Public Match Data"

After that, the site maybe will take some time to fill your past matches.
