### ISSUE TITLE
Some things (like party status, permanent buffs, etc.) are not always parsed.

### ISSUE THREAD

**Issue by n1085113** [odota/ui#1180]
So I noticed some matches are properly parsed while some others are missing things like party status, permanent buffs, replay downloads, Jist's "Get Video", and maybe some more things.

Few examples of properly parsed: [this](https://www.opendota.com/matches/3430446902), [this](https://www.opendota.com/matches/3425941166), and [this](https://www.opendota.com/matches/3446096103).

Few examples of not: [this](https://www.opendota.com/matches/3448332311), [this](https://www.opendota.com/matches/3447838404), and [this](https://www.opendota.com/matches/3449990880).

Sorry if I missed anything. Thank you, guys.

**Comment by howardchung** [comment]
The steam GC which is the source for this data has been somewhat unreliable lately.  I'll continue monitoring it and see if it improves

**Comment by howardchung** [comment]
Things seem to have improved so closing this issue.  It might pop up again from time to time, the solution is to request a re-parse when the steam GC is accepting replay salt requests :)
