### ISSUE TITLE
The MMR is not updating

### ISSUE THREAD

**Issue by hg1zadr** [odota/ui#1181]
- Windows 10 x64
-1920x1080
-Chrome/60.0.3112.113
-https://www.opendota.com/players/116999199
![image](https://user-images.githubusercontent.com/23492419/30630632-3cffe7ec-9e03-11e7-8ec4-672b0f0065a8.png)

The actual issue is that the MMR is **not updating**, last update of solo Solo MMR was on May
and Party MMR was on August 2016.

**Comment by howardchung** [comment]
Did you follow the directions here?

https://blog.opendota.com/2016/01/13/opendota-mmr-and-you/

**Comment by hg1zadr** [comment]
ow :D Didn't knew that thx :)
