### ISSUE TITLE
how use Steam ID

### ISSUE THREAD

**Issue by LordVersA** [odota/ui#1185]
hi
i use Steam login and steam give steamID , how can i use that to use Opendota API too. OpenDota Need Dota Friend Id. How can i fix this problem?

**Comment by howardchung** [comment]
You can translate between the friend ID (32bit) and steam ID (64bit):
https://github.com/odota/core/blob/master/util/utility.js#L25

```
/*
 * Converts a steamid 64 to a steamid 32
 *
 * Takes and returns a string
 */
function convert64to32(id) {
  return Long.fromString(id).subtract('76561197960265728').toString();
}

/*
 * Converts a steamid 64 to a steamid 32
 *
 * Takes and returns a string
 */
function convert32to64(id) {
  return Long.fromString(id).add('76561197960265728').toString();
}
```
