### ISSUE TITLE
"x1" in some matches

### ISSUE THREAD

**Issue by Cossack13** [odota/ui#1188]
I see mark "x1" on some matches. I always play solo, but not all matches marked with the same sign. 
![bug](https://user-images.githubusercontent.com/16056285/30749014-440586fc-9fdc-11e7-8f0c-cc5aacd463d2.PNG)

**Comment by howardchung** [comment]
The data is sometimes unavailable if the steam GC is not responding.  Requesting a re-parse should fix the issue
