### ISSUE TITLE
improve css maintainability

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1189]
Some thoughts on improving css maintainability:

* We should go one of two routes with CSS
  * Simplicity: Make it barebones, nothing but css-loader and style-loader in the webpack config
  * Power: If we decide we want more power, variables etc, then use javascript to add that functionality (like JSS)
* This means we avoid having to use semi-official solutions like postcss, which also isn't compatible with data we might want to pass from javascript
* e.g. we have two ways of making things responsive right now, either via detecting the screen size in our components and passing the appropriate styling/className, or using css media queries
* If we use JSS then our existing logic to detect screen size can be reused
* Likewise it makes sense to have common variable definitions in JS.  Having those in JSON/JS would make it straightforward to read rather than having to run it through a css processor of some kind
  * e.g. https://github.com/odota/ui/blob/master/src/components/palette.css

Material-UI v1 will use JSS for styling:
https://material-ui-1dab0.firebaseapp.com/customization/css-in-js/

Feedback?
@mike-robertson 
@blukai 
@dartharaknus 
@gu3st

**Comment by blukai** [comment]
I tried JSS some time ago, and I liked it. I think the use of JSS will be beneficial and will simplify much!
I can suggest creating a new directory in `src` called `styles` and store here `global things' like:
  - palette which contains colors
  - typography which contains text/font related stuff like font-sizes, weight..
  - theme which will be the global theme for body and app-container, I guess

We can do this gradually, many components will require changes.

**Comment by howardchung** [comment]
Currently working on moving components over to `styled-components`.

Will push a new branch and make a WIP PR soon, I'm slowly moving components over starting from the top alphabetically.  If someone else wants to help with this you could start at the bottom and we can meet in the middle :)
