### ISSUE TITLE
Story mode: add Roshan and courier kills?

### ISSUE THREAD

**Issue by TrentBartlem** [odota/ui#1190]
Seems like the kind of thing that would be worth noting in story mode.

**Comment by howardchung** [comment]
Sure, @mdiller @drusepth any interest in adding this?

I think Roshan should already be in the objectives log, courier kills I don't think so yet though

**Comment by mdiller** [comment]
Yep, Roshan is already in there. Courier kills sounds cool to add but we'd have to add it to core

**Comment by drusepth** [comment]
Do we have any documentation on how to add something to core + use it in UI? I'd probably be up for this when I get some spare time, unless someone else has tackled it first.

**Comment by howardchung** [comment]
No official documentation, although I can help with getting you pointed in the right direction.  Check the files in the `processor` directory which read the event logs emitted from the parser.  You can add those events to the `objectives` array and then access it from the API (you wouldn't need to make any schema changes that way)

**Comment by howardchung** [comment]
fixed in #1255
