### ISSUE TITLE
Bug: combat grid has heroes on wrong side

### ISSUE THREAD

**Issue by previsualconsent** [odota/ui#1196]
some of the dire heroes are with radiant and vice versa

https://www.opendota.com/matches/3465425218/combat

![image](https://user-images.githubusercontent.com/705855/30885212-f85c47b4-a2d7-11e7-8d8f-64fb200a9a7c.png)

**Comment by previsualconsent** [comment]
Huh, refreshed and went away. I had been browsing through the different tabs when this happened. 
Maybe had to do with turning off heroes in the gold graph?

**Comment by howardchung** [comment]
If you can find a reliable repro please share

**Comment by previsualconsent** [comment]
this is reliable for me
Go here: 
https://www.opendota.com/matches/3506394403/laning

sort by eff@10 and then click Combat

Browser:
Google Chrome 
Version 61.0.3163.100 (Official Build) (64-bit)

Microsoft Windows 10

**Comment by howardchung** [comment]
Ah OK, it seems the problem has to do with the sorting reordering the players so that 1-5 are no longer radiant and 6-10 are no longer dire.

**Comment by CauchyAbel** [comment]
Starting on this, trying my best :)
