### ISSUE TITLE
This user has visited recently, and replays of new matches will be automatically parsed - not?

### ISSUE THREAD

**Issue by justmeeee** [odota/ui#1198]
In Overview I have this green eye, telling me "This user has visited recently, and replays of new matches will be automatically parsed."

I ended my games 9-11 hours before now and they still havent got parsed. Can't imagine, that the queue is that long, is it?

https://www.opendota.com/players/31250349

**Comment by howardchung** [comment]
Unfortunately the queue is like 87k matches right now:
https://www.opendota.com/status

There been been occasional slowdowns all month, hopefully it will be resolved within a few days.

**Comment by justmeeee** [comment]
How is the data being processed? Even if there are avg 90k matches it seems to last too long (>15 hours). Which means that it takes at least 1.6s to parse a single match?

**Comment by howardchung** [comment]
It's not due to parsing time, it's due to not being able to fetch the replay so we can't even start

**Comment by justmeeee** [comment]
And why is that? You don't need to fetch the entire replay, it's an xml, or not?

**Comment by howardchung** [comment]
Queue is drained now, although this issue may recur from time to time.

The replay file is a binary .dem file.  However we need to make a request to the Dota 2 GC to know where to get the replay file.  If those requests aren't getting through then the replay parsing is blocked.
