### ISSUE TITLE
Sorting table broken

### ISSUE THREAD

**Issue by dricholm** [odota/ui#1206]
Sorting table seems to be broken with the latest version on git.
I found the cause and the fix, which seems to be related to a commit three days ago. (#1200)

Can I submit a pull request to fix this?

Thanks.

- **OS**: Windows 10 x64
- **Screen Resolution**: 3840x2160
- **Browser/Version**: Firefox 57.0b3 Developer Edition, Chrome 61.0.3163.100
- **Link to page with the issue**: /matches/3479726784

**Comment by howardchung** [comment]
Sure!

**Comment by dricholm** [comment]
Thanks, I will submit the PR today.
