### ISSUE TITLE
react/forbid-prop-types warnings

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1213]
According to:
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-prop-types.md

`array` and `object` should be replaced with `arrayOf` and `shape`

**Comment by cmd-kvn** [comment]
Hi @howardchung I'd like to try this!

**Comment by howardchung** [comment]
Go for it!  Fixes are pretty straightforward, just make sure to sync to latest before you start.  I fixed about half of the warnings in the last hour or so, but I'll probably be taking a break now so feel free to continue

**Comment by cmd-kvn** [comment]
@howardchung looks like you finished just before me. I'll be on the lookout for other opportunities to contribute.

**Comment by howardchung** [comment]
Yeah, I was feeling productive earlier this evening.  Lots more issues tagged with `beginner` or `hacktoberfest`!
