### ISSUE TITLE
Teamfight tab display bugs

### ISSUE THREAD

**Issue by dricholm** [odota/ui#1224]
On the Teamfight tab in the table the player column is displaying different than before: image and player name+MMR have a line break between them making the table a bit weird.

Also on the same page under the map the gold and death display is gone now.

Before:
![image](https://user-images.githubusercontent.com/32329112/31276268-f8f6b212-aad5-11e7-9005-35eaf8687cc7.png)

After:
![image](https://user-images.githubusercontent.com/32329112/31276277-03d57d26-aad6-11e7-9336-81055fbd307b.png)

Is the previous appearance good?
If yes, I can submit a PR soon.

**Comment by howardchung** [comment]
Display:
I think just putting back the gold change display will be fine

Hero line break;
Yeah, if you know how a fix would be appreciated!

**Comment by dricholm** [comment]
So under the map only the gold should be shown? Remove radiant/dire logo and death count?

About the hero line break I have been trying, but couldn't find a fix yet.
Somehow the table seems to behave differently. For example the old one was placed below the map at <1200px width. With the new version it changes <1088px.

**Comment by howardchung** [comment]
It might be due to the table not taking up the whole width.  Maybe we can make the map smaller or shrink/reduce a column?
