### ISSUE TITLE
localize string

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1232]
This string should be moved to the string file `src/lang/en-US.json`

https://github.com/odota/ui/blob/49b05dd3300ca338790481c027217aa0c691e784/src/components/Match/Overview/Overview.jsx#L73

**Comment by ThePhantomGamer** [comment]
Hi, can I take up this issue?

**Comment by dhelic98** [comment]
@howardchung  Hello, can I take up this issue?

**Comment by howardchung** [comment]
Either one of you can, it should be pretty quick

**Comment by ThePhantomGamer** [comment]
I have done this in #1236
