### ISSUE TITLE
Bug with burger menu

### ISSUE THREAD

**Issue by Luchanso** [odota/ui#1233]
I found bug in BurgerMenu - when I tap on element, menu don't close.

**Comment by howardchung** [comment]
yeah, I'm actually looking at that now

**Comment by Luchanso** [comment]
If you change `onTouchTap` on `onClick` it will be working

**Comment by Luchanso** [comment]
In BurgerMenu.jsx:41

**Comment by Luchanso** [comment]
If you wan't i can fix it and fix PropTypes in BurgerMenu?

**Comment by howardchung** [comment]
There's actually a separate issue where only the text part of the link actually works, so I'm looking into fixing that as well
