### ISSUE TITLE
Make recharts responsive on mobile

### ISSUE THREAD

**Issue by howardchung** [odota/ui#1242]
Might be as simple as wrapping the charts in the ResponsiveContainer that Recharts provides, but I haven't investigated.

**Comment by maridilip** [comment]
Solo MMR Distribution
- Is this chart to me made responsive?

**Comment by howardchung** [comment]
There are a bunch of them, they are all in the Visualizations/Graphs directory though

**Comment by maridilip** [comment]
http://localhost:3000/Visualizations/Graphs this url returns no graphs

**Comment by howardchung** [comment]
I was referring to the code in `src/components/Visualizations/Graphs`.  You can edit the DistributionsGraph file to see if the responsive container works for the MMR Distribution graph
