### ISSUE TITLE
Histogram Fields

### ISSUE THREAD

**Issue by pritishvaidya** [odota/ui#1257]
I was able to figure all the histogram field names from the opendota.com, but could you provide me the valid fields for `Observers Purchased`, `Sentries Purchased`, `Gems Purchased`, `Rapiers Purchased`, `Actions Per Minute` and `Map Pings` since I was not able to find them in the docs.

**Comment by howardchung** [comment]
https://github.com/odota/ui/blob/49b05dd3300ca338790481c027217aa0c691e784/src/components/Player/Pages/matchDataColumns.js
