### ISSUE TITLE
Invert color bar logic for time dead

### ISSUE THREAD

**Issue by WillyWinkel** [odota/ui#1263]
I would like to suggest an enhancement.

Considering the match details -> Performance -> color of the time dead bars.
Assuming a good time dead is short, and assuming a green color indicates a good performance, I would suggest to enhance the experience by turning the scale around.
Thereby short death would be shown green and long death red.

**Comment by CauchyAbel** [comment]
I will take a look at this one today, doesn't seem too hard to implement.

**Comment by howardchung** [comment]
IIRC there was a discussion about this previously and apparently these are the colors that are used in the client, so we kept it for consistency.  Can't find the thread ATM, I think @dartharaknus was involved in the discussion?

**Comment by howardchung** [comment]
I misread this issue originally, this is referring to the green->red scaling for time dead, not the K/D/A bar color scheme on the matches list.
