### ISSUE TITLE
You should be able to hide your MMR on your profile.

### ISSUE THREAD

**Issue by hntd187** [odota/ui#1282]
Dotabuff has a feature where you can hide your MMR in your public profile, which I think would be useful here. 

Otherwise for me it shows a 2 year old MMR which is otherwise wrong. I could probably implement this myself with a bit of guidance on what would be needed in the back end, but I'd imagine UI side it'd just be return it or don't return it.

**Comment by howardchung** [comment]
Rather than hide it I think the consensus is to show how old it is so the data is in the proper context:
https://github.com/odota/ui/issues/1183
