### ISSUE TITLE
Handle new heroes in Combat and Log Tabs 

### ISSUE THREAD

**Issue by ABigg** [odota/ui#1294]
Clicking the Combat or the Log tab in matches where the new heroes have been played results in this:

![opendotesbug](https://user-images.githubusercontent.com/33290444/32283778-f260e30e-beea-11e7-8a84-1dd3ee1a19b6.png)

The issue can also be replicated on Chrome:

![opendotabug2](https://user-images.githubusercontent.com/33290444/32283880-39ae9d50-beeb-11e7-8cdd-9ed8a3ec3851.png)

It doesn't seem to happen in matches where the new heroes were not played.

**Comment by howardchung** [comment]
Issue is fixed by adding new heroes to hero list, but we should still handle this without crashing

**Comment by howardchung** [comment]
This should not be too hard to do, although now that the data for the new heroes has been added, you might need to repro it by faking some data or modifying the heroes object imported from dotaconstants to simulate not having a hero object for a new ID.
