### ISSUE TITLE
Unparseable match yesterday

### ISSUE THREAD

**Issue by hematic** [odota/ui#1295]
https://www.opendota.com/matches/3534483261

This match will not parse either with me clicking the request parse button on the website, or via me sending the proper post to the rest API.

**Comment by howardchung** [comment]
Likely related to https://github.com/skadistats/clarity/issues/150

@spheenik is looking at it

**Comment by hematic** [comment]
Well, cant ask for more than that ;)

**Comment by spheenik** [comment]
Should work now. Plz test with newest 2.2-SNAPSHOT.

**Comment by howardchung** [comment]
Looks like it's working now!
