### ISSUE TITLE
vision tab still uses 7.06 map

### ISSUE THREAD

**Issue by tobyfloyd** [odota/ui#1299]
the vision tab still uses the  7.06 mini map instead of the new 7.07 map.

**Comment by howardchung** [comment]
do we have a new map image to use?

**Comment by tobyfloyd** [comment]
yeah there is a new one.


you can find for example at the dota 2 wiki:


https://dota2.gamepedia.com/Minimap
https://dota2.gamepedia.com/File:Minimap_7.07.png





-----Ursprüngliche Mitteilung----- 
Von: Howard Chung <notifications@github.com>
An: odota/ui <ui@noreply.github.com>
Cc: tobyfloyd <rrealtobi@aol.com>; Author <author@noreply.github.com>
Verschickt: So, 5. Nov 2017 11:46
Betreff: Re: [odota/ui] vision tab still uses 7.06 map (#1299)



do we have a new map image to use?
