### ISSUE TITLE
Story tab gold difference text overlaps

### ISSUE THREAD

**Issue by patrickdevarney** [odota/ui#1306]
Gold difference amount and percentage overlaps total gold shown. Is usually noticed on higher resolution monitors (1440p). Can be emulated by Ctrl+- to zoom out in browser if on 1080p.

![capture](https://user-images.githubusercontent.com/11896025/32518885-8f59774a-c3d0-11e7-94bf-aeeccb25928f.PNG)

**Comment by howardchung** [comment]
@mdiller ?

**Comment by mdiller** [comment]
Huh that's weird. I'll take a look when I have time
