### ISSUE TITLE
Explorer for regular matches? (feature request)

### ISSUE THREAD

**Issue by quole** [odota/ui#1309]
Explorer is awesome for pro matches. 

Is there any chance of taking a random sample of 10,000 or 100,000 regular matches (per patch, per game mode) and making them available with a similar interface?

**Comment by howardchung** [comment]
I've considered it, although it may be quite space-intensive to store many tens of thousands of fully parsed public matches.

For now, a sample of public matches is available in the public_matches/public_player_matches tables (but with only a small subset of columns)

**Comment by quole** [comment]
Ah! Somehow I missed those public match tables... with 15,604,577 entries! They'd actually be perfect for what I'm trying to do (namely a histogram with the length of Techies games vs all games). 

The only thing that seems to be missing, which almost all entries lack, is which patch they are from.

 - [here's a query showing the number of public vs pro matches per match](https://www.opendota.com/explorer?sql=select%20patch%2C%20count(public_matches.match_id)%20as%20public_match_count%2C%20count(matches.match_id)%20as%20pro_match_count%0D%0Afrom%20match_patch%20%0D%0Aleft%20join%20public_matches%20on%20(match_patch.match_id%20%3D%20public_matches.match_id)%0D%0Aleft%20join%20matches%20on%20(match_patch.match_id%20%3D%20matches.match_id)%0D%0Agroup%20by%20match_patch.patch%0D%0Aorder%20by%20match_patch.patch%3B%0D%0A&format=)
 - [here's one just of the number of public matches per patch, including those without a patch number listed (null)](https://www.opendota.com/explorer?sql=select%20patch%2C%20count(public_matches.match_id)%20as%20count%0D%0Afrom%20public_matches%0D%0Aleft%20join%20match_patch%20on%20(public_matches.match_id%20%3D%20match_patch.match_id)%0D%0Agroup%20by%20match_patch.patch%0D%0Aorder%20by%20match_patch.patch%3B%0D%0A&format=)

Is there any way to get the first and last match IDs per patch? (Other than using the [first and last pro game IDs per patch](https://www.opendota.com/explorer?sql=select%20patch%2C%20min(match_id)%20as%20first_match_id%2C%20max(match_id)%20as%20last_match_id%0D%0Afrom%20match_patch%20%0D%0Agroup%20by%20match_patch.patch%0D%0Aorder%20by%20match_patch.patch%3B%0D%0A&format=), which I guess might work well enough anyway, 364,920 matches between the first and last match_ids which are actually listed as '7.07' [3534655441 and 3553474678]. Cool. Never mind. Thanks)

**Comment by howardchung** [comment]
match_patch only contains pro matches.

public_matches may include pro matches, they are not mutually exclusive.

**Comment by quole** [comment]
Yup, thought that might be the case. All good. If there was a table of first and last matches per patch it would be easier to work out which patch each public game was (assuming match IDs are in order, etc), but this makeshift way works well enough (see link above on "first and last pro game")

Anyway here's the chart I made from data from the SQL interface:

https://imgur.com/ISVsdUz

I haven't posted it to Reddit yet.

**Comment by howardchung** [comment]
I actually made this!  #1322
