### ISSUE TITLE
TeamfightEvent sometimes renders no heroes on losing side

### ISSUE THREAD

**Issue by blueish** [odota/ui#1312]
steps to reproduce:
1. go to https://www.opendota.com/matches/3557630134/story
2. Scroll to the bottom to see this:
![noheros](https://user-images.githubusercontent.com/6327663/32755522-8b775dc2-c88a-11e7-8459-23d7e24a25a2.PNG)

Logging out the TeamfightEvent props reveals that some heroes have deaths set to zero, so that the deaths variable only contains the winning team heroes (relevant line: https://github.com/odota/ui/blob/d4076333a26471cd3ebc2958e3fb584cd025b362/src/components/Match/MatchStory.jsx#L567)

Not sure exactly where the data is coming from so I can't trace it further, but that's probably a good place to start.

**Comment by howardchung** [comment]
@mdiller shouldn't it say "for no heroes"?

**Comment by mdiller** [comment]
So it looks like the reason why this is happening is I only accounted for the winning team having no deaths. I didn't realize you could win a teamfight when four of your players died and none of theirs did lol.

Guess I'll make a new string for when that happens.

**Comment by howardchung** [comment]
I'm guessing it was gold from the buildings, or maybe a hero died weirdly (shared kill credit?) and doesn't get picked up

**Comment by howardchung** [comment]
I'm really not sure what happened (https://www.opendota.com/matches/3557630134/teamfights)

Looks like some kind of fountain farming, but if someone wants to look at the replay maybe we can get some answers :)

**Comment by mdiller** [comment]
Hmmm yeah maybe. I'm tempted to watch the replay and look. I thought I've been in some one sided games but heres this game with 139 - 5 kills at 43 minutes in.

**Comment by howardchung** [comment]
probably the dark willow fountain camped the dire team, killed 4 heroes, got killed by the fountain, and gave a ton of gold to everyone on dire.  I'm not sure why the death doesn't show up on the teamfight log though

**Comment by mdiller** [comment]
Hmmmm yeah maybe, that'd make sense. I'm going to check the replay.

**Comment by mdiller** [comment]
What a strange game.

This happened near the end of the game, and the entire radiant team is afk in dire's fountain, killing anyone who spawns instantly.

Ancient Apparition (on dire's team) is farming in middle lane for the whole "teamfight." his farming plus the gold he gets from his three disconnected teammates means he gains about 1400 gold during the fight. That gold gain is more than the gold the radiant team got for killing four of his teammates as they spawned, and so i guess technically he "won" the "teamfight"

**Comment by mdiller** [comment]
Looks like they went to the fountain at 30 minutes in and didn't leave until the end of the game

**Comment by mdiller** [comment]
The second one was pretty much the same thing except the AA took radiant mid rax and t3 so its a bigger gold swing to his team

**Comment by mdiller** [comment]
The AA ended up just pushing and winning the game because I guess the radiant just didn't care?

**Comment by howardchung** [comment]
https://www.youtube.com/watch?v=6DGNZnfKYnU

I just noticed that dire won haha

**Comment by mdiller** [comment]
lol yeah
