### ISSUE TITLE
MMR is showed incorrectly

### ISSUE THREAD

**Issue by arcry2009** [odota/ui#1315]
Gained +25 aren't added to solo mmr counter. Mmr is displayed in dota 2 profile.Is it possible to fix?
https://www.opendota.com/players/55131418
https://steamcommunity.com/profiles/76561198015397146/

**Comment by howardchung** [comment]
Sometimes it doesn't update immediately so when we check it hasn't changed yet.  It will try every time you finish a game, so eventually it should update (but may be a game behind)
