### ISSUE TITLE
Benchmarks: Hero Healing Per Minute

### ISSUE THREAD

**Issue by pennomi** [odota/ui#1325]
On the Benchmarks tab, there's a column for "Hero Healing per Minute". For most heroes, this value is at zero. However, even though the value is zero, it places the player at a percentile.

It's possible I just don't understand what the percentile means here, but it really doesn't make sense to me; if I did zero healing, that means I would be in the 0th percentile, right? Or is it the other way around, N percent of people playing this hero did no healing?

Either way I think the UI could use a little explanation or tweaking. Would it make sense to remove the data from matches where the hero did no healing and display these columns differently? So you're only being compared to matches where some healing was done by that hero.

**Comment by howardchung** [comment]
I think the standard definition of percentile is the percent of observations that fall at or below the indicated value.  0 is a valid value, so I don't think we should omit it.

If a percentile is given for a 0 value, that's the percent of observations that was 0.  I think the tooltip indicates "equal or less than"

**Comment by pennomi** [comment]
Yep you're right. It feels a bit strange to be given a green "all is good" for a stat that you did nothing on, but I suppose that means you're playing the hero as intended, so in fact things are all good.
