### ISSUE TITLE
Just joined and player data nonexistent

### ISSUE THREAD

**Issue by scottcandy34** [odota/ui#1328]
My roommate just found this and was like you join. when i did it refused to display anything about my profile. i have tried to refresh the page and the refresh button but it still does not load my game data. i would love to check this out more but cant because it refuses to load anything. i use the same account name.

**Comment by coreymaher** [comment]
@scottcandy34 It looks like you haven't enabled "Expose Public Match Data" in your dota 2 settings.
It should be under options -> advanced options -> social -> Expose Public Match Data.

Once you enable that you should be able to hit the refresh button on your profile again and then matches will start showing up in a little while.

**Comment by scottcandy34** [comment]
@coreymaher Thx that fixed it right up....
