### ISSUE TITLE
Add propTypes for all component

### ISSUE THREAD

**Issue by mike-robertson** [odota/ui#145]
Early on I stupidly decided we could skip this, but I think that (at least going forward), we should add propTypes to components we create and we should circle back at some point (at the same time as unit tests probably) to add propTypes into existing components.

**Comment by dartharaknus** [comment]
I think this is done, right?

**Comment by howardchung** [comment]
Not for all components.  There's a lint option we disabled.  If we turn it on it'll start erroring for the ones where we're missing this.

**Comment by howardchung** [comment]
Not for all components.  There's a lint option we disabled.  If we turn it on it'll start erroring for the ones where we're missing this.

**Comment by howardchung** [comment]
Not for all components.  There's a lint option we disabled.  If we turn it on it'll start erroring for the ones where we're missing this.

**Comment by howardchung** [comment]
maybe if we make it emit warnings it'll motivate us to do this

**Comment by howardchung** [comment]
I enabled warnings, there are currently about ~410 violations.

**Comment by howardchung** [comment]
@covertPZ any progress on this?

**Comment by covertPZ** [comment]
I haven't gotten around to working on any of this yet. I guess before I do, we should resolve the question you posed in #861 about how we want to define for consistency.

**Comment by Phrynobatrachus** [comment]
any preference for the #861 Q? I could work on this.

**Comment by howardchung** [comment]
I think since react moved to the `prop-types` package the issue was resolved, you just import that package and use the types from it.

**Comment by murilodag** [comment]
Hello @howardchung, could I work on this issue?

**Comment by howardchung** [comment]
Yes, of course!

**Comment by murilodag** [comment]
Should I open one PR  per component or a single PR for all of them?

**Comment by howardchung** [comment]
You can probably just open one for all of them.  I'm working on moving the CSS over to styled-components in #1203 , hopefully it won't conflict too much
