### ISSUE TITLE
cleanup 🦄

### ISSUE THREAD

**Issue by blukai** [odota/ui#148]
Do we need these dependencies? 
[react-motion](https://github.com/odota/ui/blob/master/package.json#L39)
[redux-devtools](https://github.com/odota/ui/blob/master/package.json#L46)
[expose-loader](https://github.com/odota/ui/blob/master/package.json#L67)
[react-addons-css-transition-group](https://github.com/odota/ui/blob/master/package.json#L36)

And [.nojekyll](https://github.com/odota/ui/blob/master/.nojekyll) file - I didn't found any files or directories that start with underscores.

**Comment by mike-robertson** [comment]
I'm not aware of using any of those. If it builds without them then I think it's good to remove them.

**Comment by howardchung** [comment]
Yeah, I think they'll all good to remove.
