### ISSUE TITLE
rankings display fixes

### ISSUE THREAD

**Issue by howardchung** [odota/ui#155]
http://beta.opendota.com/players/88367253/rankings

- [x] last played always shows as "never".  I think this is due to not returning the last played date on this endpoint.  We should have an option on the hero cell to hide this value.
- [x] We should make the rank an ordinal number.  There's a utility function in core to do this (or just Google for it)

- [x] Current UI has context coloring based on the percentile (green/blue/dark blue/yellow/red).  We can add this to the new UI.

- [x] Hero should link to rankings page

- [x] Rank column should only add the english in the display function. Otherwise sorting is as a string and doesn't sort properly.

**Comment by mike-robertson** [comment]
edited with a bug I found

**Comment by blukai** [comment]
>Hero should link to rankings page

@howardchung, Maybe each hero name in each table should link to hero page?

**Comment by howardchung** [comment]
I think the expected behavior on most tabs would be to link to a filter with that hero selected.  Going to the hero page is a special case only on the rankings page.

**Comment by blukai** [comment]
> Rank column should only add the english in the display function. 

This should be done after this https://github.com/odota/ui/blob/master/src/lang/index.js#L1 I guess.
>Otherwise sorting is as a string and doesn't sort properly.

Sorting fixed by https://github.com/odota/ui/pull/243/files#diff-d0fed5b44f5647097f88d07362f2f4cbR20
