### ISSUE TITLE
make svg social icons

### ISSUE THREAD

**Issue by blukai** [odota/ui#157]
steam, twitter, discord, github, ...more?
as [example](https://github.com/odota/ui/blob/bf82d9516c1feb30dbda69d989b58e750a268df0/assets/IconCheese.jsx)
@howardchung, @mike-robertson, should I move icons, like this, to /components/Icons ?

**Comment by mike-robertson** [comment]
yea that makes sense. You should probably have a reddit one as well is my guess.

**Comment by howardchung** [comment]
We currently don't need a Reddit one anywhere, but we could add it proactively
