### ISSUE TITLE
Dir structure update + webpack absolute paths

### ISSUE THREAD

**Issue by mike-robertson** [odota/ui#160]
I think that we should update our project structure to something like this:
```
src/
  components/
  etc./
  index.jsx
webpack.config.js
package.json
```
This will allow us to leverage doing this in webpack: http://moduscreate.com/es6-es2015-import-no-relative-path-webpack/
```js
import MyComponent from '../../../MyComponent';
// becomes
import MyComponent from 'components/MyComponent';
```

**Comment by mike-robertson** [comment]
Actually, on more investigation, I have found that doing this will break our ESLint for imports which I believe is more useful since it will warn us when we accidentally mess up import statements (which can lead to very weird bugs).

**Comment by mike-robertson** [comment]
Actually, on even more investigation, I believe there is a way around this.

**Comment by howardchung** [comment]
done in #179
