### ISSUE TITLE
display "inactive" icon

### ISSUE THREAD

**Issue by howardchung** [odota/ui#161]
* Inactive: Currently the behavior is to display the "tracked" icon if tracked and nothing if the user is not tracked.  I think it's beneficial to display for example a "Zzz" icon to indicate the user is inactive.  That way the user can more quickly figure out why their matches aren't being parsed.

* Currently no icon is displayed for 0 cheese.  I recently added this in the current UI to aid spacing/layout issues (easier to debug if it shows up on all pages).

**Comment by blukai** [comment]
I believe that display the cheese icon for those who don't have it has no sense.

**Comment by howardchung** [comment]
OK, that makes sense.  Will change to only the first item.
