### ISSUE TITLE
handle undefined routes (404)

### ISSUE THREAD

**Issue by howardchung** [odota/ui#167]
Currently we just display a blank page (probably some javascript exceptioning somewhere).

We should either create a 404 page or redirect users to root.

**Comment by mike-robertson** [comment]
@blukai do you want to design what that 404 page looks like? I can route to a generic 404 but maybe you can come up with something cool? I'll assign this one to myself unless @howardchung was planning on doing it.

**Comment by howardchung** [comment]
Go ahead.  Here's the current page: https://www.opendota.com/404

**Comment by mike-robertson** [comment]
ugh, there's no way to do this in react-router natively (at least as far as I can tell). I can probably make something work but it won't be super simple.

**Comment by howardchung** [comment]
Can you use a wildcard route placed at the end?

**Comment by mike-robertson** [comment]
yes, I didn't read the docs very thoroughly.

**Comment by blukai** [comment]
@mike-robertson Sure, I'll come up with something.
As the basis I prefer clone of /components/Home 
✌️

**Comment by mike-robertson** [comment]
Ok, I just have some simple div with text in it, it will render inside of the app component (header and footer will be included).
