### ISSUE TITLE
linked accounts

### ISSUE THREAD

**Issue by blukai** [odota/ui#169]
Allow users connect their other steam profiles (since some players have a few accounts), and display them in dropdown like it does Google.

![](https://www.google.com/safetycenter/images/tools/26-1.png)

@howardchung, @mike-robertson, What do you think about it?

**Comment by howardchung** [comment]
This would require a backend change to track the links. (so this issue should probably go in odota/core).

We don't have a way to verify account ownership.  We could allow users to link accounts for easier access without verification.

**Comment by blukai** [comment]
> We don't have a way to verify account ownership. We could allow users to link accounts for easier access without verification.

If user already logged allow him to connect other profile through steam login? Make option to select an main account and secondary.

**Comment by howardchung** [comment]
I don't think this is possible to do securely.  Logging in through Steam just has Steam verify that a user has logged in and that they own the Steam account logged in with.  It doesn't tell us that it is linked with any other account.

I am not sure if openid supports passing parameters that get sent back on the return.  If it does, I suppose it would be possible to generate a random token that's sent to Steam, and returned when login is complete.  I haven't tested this though.

**Comment by blukai** [comment]
I have no idea how to realize it properly and securely, but anyway I think it's would be a nice feature

**Comment by mike-robertson** [comment]
If we could do this, it would allow use to display information across all their accounts in all the data. It would require a lot of work to get right though (if even possible), and I'm not sure how many people would make use of it.

**Comment by howardchung** [comment]
This is an issue for odota/core.  Reopen there if we want to keep tracking it (but I don't have a solution for this immediately).
