### ISSUE TITLE
Docker for UI

### ISSUE THREAD

**Issue by howardchung** [odota/ui#176]
I don't use Docker for odota/ui myself, but it might be useful for people who like to run everything in Docker.

This will be a lot simpler than the configuration for odota/core.  There's only a single container and no linking needed.

perhaps @dartharaknus or @Daerdemandt might be interested.

**Comment by mike-robertson** [comment]
I think as a prereq to this we should do the directory update. But I won't be able to do that easily unless we freeze PR's for a bit because merging is really difficult.
