### ISSUE TITLE
"sum" column property for tables

### ISSUE THREAD

**Issue by howardchung** [odota/ui#191]
Extend table component to compute sums for specified columns.

**Comment by howardchung** [comment]
* We could add another "sumFn" prop to each column that defines how the value should be treated for sum purposes.
* If the Table component finds any of its columns has a sumFn, it renders an additional row at the bottom of the table
* It sums the columns that have the property and puts the value in the cell.
* Perhaps we could reuse the sortFn since it will likely be the same.
* This value would also be used for relative magnitude bars (#86)

**Comment by dartharaknus** [comment]
@howardchung Update on this?

**Comment by howardchung** [comment]
@mike-robertson probably has the most context on this, but anyone could do it.  I'd like to have this eventually since table sums are useful, but this is not a release blocker.
