### ISSUE TITLE
Sponsor integrations

### ISSUE THREAD

**Issue by howardchung** [odota/ui#200]
- [x] Dotacoach
- [x] Jist
- [x] becomethegamer
- [x] vpgame
- [x] lootmarket
- [x] stanza (maybe?)

**Comment by howardchung** [comment]
complete except for the dotacoach player page issue which @kennsippell is fixing this week

**Comment by kennsippell** [comment]
fixed. sorry for the delay

**Comment by howardchung** [comment]
Could you also update the text on the page to "OpenDota"?

https://dotacoach.org/Hire/Yasp?matchID=2752720849&userSteamId=88367253

**Comment by kennsippell** [comment]
Ya made that change.  Deployments were blocked (unrelated), so you couldn't see it. The url https://dotacoach.org/Hire/OpenDota also works if you care to make that change on your end
