### ISSUE TITLE
404 error when loading fonts

### ISSUE THREAD

**Issue by howardchung** [odota/ui#202]
It appears that the browser is firing requests to load fonts, and it is case sensitive.  Repro: Visit any page on the production SPA

Requests:
http://beta.opendota.com/assets/fonts/PTSans/pts75f_w.woff
http://beta.opendota.com/assets/fonts/PTSans/pts75f_w.ttf

Shouldn't these be bundled with webpack?

**Comment by howardchung** [comment]
Might be a webpack config issue.  Perhaps we need to use file-loader on .woff files?
```
    }, {
      test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url-loader?limit=10000&minetype=application/font-woff&name=[hash].[ext]',
    }, {
      test: /\.(ttf|eot|svg|jpg|gif|png)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'file-loader?name=[hash].[ext]',
    }, {
```

**Comment by blukai** [comment]
@howardchung, I guess we can go this way https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/#approach-b ? What do u think?

**Comment by howardchung** [comment]
Yes that sounds like a good idea
