### ISSUE TITLE
Ability is missing from the data

### ISSUE THREAD

**Issue by roman-kosov** [odota/ui#204]
Match:
[https://www.opendota.com/matches/2670620561](https://www.opendota.com/matches/2670620561)

Screen:
![https://cdn.discordapp.com/attachments/144629812982448128/230595477727346689/0.png](https://cdn.discordapp.com/attachments/144629812982448128/230595477727346689/0.png)

Correct ability is:
![Correct ability is](http://www.dotabuff.com/assets/skills/beastmaster-call-of-the-wild-boar-5580-c02e9ebd79f9030691b5984ed6b0521cb5da4963cb5a806dad8af3c7199d0842.png)

**Comment by howardchung** [comment]
The ID to key mapping is present:
https://raw.githubusercontent.com/dotabuff/d2vpkr/master/dota/scripts/npc/npc_abilities.json

However, the expanded ability information is not:
http://www.dota2.com/jsfeed/abilitydata

Solutions:
* Manually add this data to abilitydata, like what we do here: https://github.com/odota/dotaconstants/blob/master/constants.js#L75
* Find a better data source for the ability data

**Comment by howardchung** [comment]
merge with #344
