### ISSUE TITLE
trends bugfixes

### ISSUE THREAD

**Issue by howardchung** [odota/ui#228]
- [ ] data needs to be reversed before computing cumulative average (oldest to newest)
- [ ] filter out undefined values (for parsed fields on unparsed matches)

**Comment by Roshanjossey** [comment]
Hey @mike-robertson: I'm working on this issue. 
Currently looking in to `https://github.com/odota/ui/blob/master/src/selectors/trends/getPlayerTrend.js`

**Comment by mike-robertson** [comment]
Hey Roshan. I appreciate the help but this was already an issue we solved. It simply needed to have the PR created (which I have done now). Please let me know if you have any questions about other issues!

**Comment by Roshanjossey** [comment]
@mike-robertson: Thank you for your reply. I'm also looking in to #81 and #104.

I think it'll help a lot if we attach screen shots for those issues and while sending PRs.

Anyways lets take the conversation in those threads.
