### ISSUE TITLE
Webpack not watching when in docker

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#244]

**Comment by dartharaknus** [comment]
@howardchung Can you try this on your computer?

**Comment by howardchung** [comment]
Yeah, I tested and the events don't seem to be picked up by webpack-dev-server to trigger a rebuild.  Not sure what the cause is.

**Comment by dartharaknus** [comment]
Can you fix this? I can't do it on windows.

**Comment by howardchung** [comment]
I don't know if it's a problem with our code that we can fix easily.  My guess is that the file change events that Docker should generate (since the working directory is mapped to the docker container) aren't being recognized.

**Comment by howardchung** [comment]
Maybe this?

https://github.com/webpack/webpack-dev-server/issues/143#issuecomment-244592492

**Comment by dartharaknus** [comment]
First suggestion didn't work for me. I can't try the config change though since I don't see any watch option anywhere at all. Remember that we run `npm start` which runs `webpack-dev-server --compress` without any watch option given.

**Comment by howardchung** [comment]
It would be in the webpack.config.js file.

**Comment by dartharaknus** [comment]
Nope, there isn't.

**Comment by howardchung** [comment]
I mean, that's where it would go.  It won't be one of the keys in the config object right now, you have to add it.
