### ISSUE TITLE
Bad footer and navbar link (Safari)

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#247]
On my 1280x800p mac.

![](http://i.imgur.com/WZVgvSq.png)

**Comment by blukai** [comment]
Is it still a problem? What browser are u using?

**Comment by dartharaknus** [comment]
Safari. And yes, it still exists.

**Comment by blukai** [comment]
@dartharaknus, can you try to disable body's height?

![image](https://cloud.githubusercontent.com/assets/20866892/20072980/23ba2794-a533-11e6-9879-8492f05be7ff.png)

If this will fix the problem I'll make a pr or someone else can 🦄

**Comment by dartharaknus** [comment]
That fixes the footer. What about the navbar?

**Comment by blukai** [comment]
Idk, I'll try find out via browserstack.com 😛

**Comment by blukai** [comment]
Yeah, disabled width in `.tabContainer` works.
![image](https://cloud.githubusercontent.com/assets/20866892/20079173/32ab3cb6-a54c-11e6-9dbc-5d580d0de4d4.png)

**Comment by blukai** [comment]
btw hacktoberfest was ended
