### ISSUE TITLE
Explore using Yarn

### ISSUE THREAD

**Issue by mike-robertson** [odota/ui#274]
Facebook/google just came out with a layer of NPM which has solved a lot of common issues people have with npm (most notably consistency, security, and performance). I think it's worth looking into swapping over (could be as simple as just changing some commands in npm scripts from npm i to yarn install.).

https://yarnpkg.com/

**Comment by blukai** [comment]
> Ultra Fast.
Yarn caches every package it downloads so it never needs to again.

First install with `yarn` takes more time than `npm` and I don't think I wanna cache packages.
[pkg that I used](https://github.com/blukai/ui/blob/master/package.json)
`yarn install`
![image](https://cloud.githubusercontent.com/assets/20866892/19346252/25a95ce2-914b-11e6-8ed2-9594726a020c.png)

`npm install`
![image](https://cloud.githubusercontent.com/assets/20866892/19346538/8b33bcf0-914c-11e6-8248-125de836ccfb.png)

🦄

**Comment by Roshanjossey** [comment]
Let's make a decision on this thinking about the future of this project. We might be using more packages in the future. yarn might turn out to be a good choice for the future. I haven't started using yarn yet but read a few articles 
- https://medium.com/@shuvohabib/from-npm-to-yarn-should-i-go-for-it-or-not-8d71480ed270#.jwbfofrdf
- https://scotch.io/tutorials/yarn-package-manager-an-improvement-over-npm

I liked the `.lock` feature the most. That is something I've been missing in js world coming from ruby ecosystem. It'll provide more determinism. Also I happen to work offline much so this will help me a lot.

**Comment by howardchung** [comment]
I think we're sticking with npm--but feel free to comment/reopen if we want to explore this in the future.
