### ISSUE TITLE
Responsive design for player and match pages

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#278]
This issue tracks the implementation of Responsive design for player and match pages in the app.
## Player Pages
- [ ] Overview
- [ ] Matches
- [ ] Heroes
- [ ] Peers
- [ ] Pros
- [ ] Counts
- [ ] Records
- [ ] Histograms
- [ ] Trends
- [ ] Items
- [ ] Wardmap
- [ ] Wordcloud
- [ ] MMR
- [ ] Rankings
## Match Pages
- [ ] Overview
- [ ] Benchmarks
- [ ] Performance
- [ ] Combat
- [ ] Farm
- [ ] Purchases
- [ ] Graphs
- [ ] Casts
- [ ] Objectives
- [ ] Vision
- [ ] Actions
- [ ] Teamfights
- [ ] Analysis
- [ ] Cosmetics
- [ ] Logs
- [ ] Chat

**Comment by howardchung** [comment]
this issue seems kind of generic.  should we instead create issues for particular features that would help in making the pages responsive, like support for splitting wide tables into tabs?

**Comment by dartharaknus** [comment]
Yes, I think we should subdivide.

**Comment by howardchung** [comment]
Closing as this is very general.  Open new issues for specific deliverables.
