### ISSUE TITLE
prettify match analysis

### ISSUE THREAD

**Issue by howardchung** [odota/ui#289]
Currently, this is just a data dump of the raw data.

**Comment by vikashvverma** [comment]
@howardchung I would like to help. Can you give me a head start?

**Comment by howardchung** [comment]
Sure, although I'll probably tackle this tonight or tomorrow.

Current UI:
http://www.opendota.com/matches/2728551600/analysis

Beta UI:
http://beta.opendota.com/matches/2728551600/analysis

Basically, the beta UI needs some styling improvement.  It probably won't match the current one exactly.
