### ISSUE TITLE
functional navbar/search on mobile

### ISSUE THREAD

**Issue by howardchung** [odota/ui#295]
Make the navbar/search widget work effectively on mobile.

**Comment by recurza** [comment]
Could be a good idea to add a hamburger menu (for mobile), with the search at the top

**Comment by blukai** [comment]
@recurza Do it

**Comment by mike-robertson** [comment]
@recurza if you look in the history, you should be able to find an app bar component or nah drawer. You can probably use that and just change what is contained within it. You could also use redux-responsive to only display that component at smaller screen sizes. I was planning on doing something for that soon but if you'd like to contribute I don't mind doing less work 👍

**Comment by recurza** [comment]
Ok, will do 😁

**Comment by howardchung** [comment]
Sounds good!  Let me know if you're interested in being a regular contributor/code reviewer and we can add you as a project member so you can own issues and create branches
