### ISSUE TITLE
React SPA

### ISSUE THREAD

**Issue by howardchung** [odota/ui#3]
Continuation of https://github.com/yasp-dota/yasp/issues/889

MVP:
- [x] architecture @mike-robertson
- [x] build search page @bguzryanto
- [x] build request page @howardchung (WIP)
- [x] build heroes pages (rankings/benchmarks) @marvizm, @bguzryanto (WIP)
- [ ] build distributions page @gu3st, @howardchung (WIP)
- [ ] build match pages @howardchung (WIP)
- [ ] build player pages @mike-robertson (WIP)
- [x] player page filtering @mike-robertson (WIP)
- [ ] build home page @albertcui
- [ ] tooltips
- [ ] make usable on mobile

Telemetry/Sponsorship:
- [ ] make google analytics work @howardchung
- [x] ~~adsense @albertcui~~ (dropping adsense)
- [ ] move donation code to own app @albertcui
- [ ] dotacoach @kennsippell
- [ ] jist @albertcui 
- [ ] pvgna @albertcui 
- [ ] becomethegamer @albertcui 

Validation:
- [ ] test login @howardchung

Bonus:
- [ ] mmstats @albertcui 
- [ ] status page
- [ ] banner (dismissable)
- [ ] page titles

People:
@howardchung
@albertcui
@mike-robertson
@gu3st 
@stevenla
@Iparke
@bguzryanto
@Shenlok
@kkotwal94
@masad-frost
@bmulcahy
@Marvizm

Please indicate what you'd like to work on and coordinate with others working on the same area to avoid too many merge conflicts :)

**Comment by Marvizm** [comment]
Can I also take part? I Have some ideas about player pages and I think Rankings, Benchmarks can be merged in one page that contents rankings, benchmarks and may be in future more things.

**Comment by howardchung** [comment]
Added

**Comment by gu3st** [comment]
Possible replacements for jQuery libraries that main site uses:

select2 - http://jedwatson.github.io/react-select/
qtip2 - <unknown, although it's for tooltips, which could be implemented by each component>
datatables - mike is writing something to replace this dependency

**Comment by gu3st** [comment]
I've started on the distributions page in my own build gu3st/ui@b1b7708

It's not much so far.  I should be able to keep using c3.js as well (as it is a good solution) as it doesn't require jQuery or anything gross.

**Comment by mike-robertson** [comment]
On a styling note, we should try to use material-ui components when we can so that the general look and feel is consistent. Things like buttons, icons, etc. I've loaded in the material icons font, Google has a documentation page of all the options. Then you can just stuff the name into a FontIcon component from material-ui

**Comment by bmulcahy** [comment]
https://materialdesignicons.com/ another good resource for the material design look and feel

**Comment by bguzryanto** [comment]
hi @howardchung I would like to work on search page. is there any API documentation related to search, I don't find any search documentation on swagger.

**Comment by howardchung** [comment]
I didn't document it but you can work based on the source:
https://github.com/yasp-dota/yasp/blob/master/routes/api.js#L144

It's pretty simple, just a query param q with the search string.

You can add it to the Swagger spec if you like

**Comment by bguzryanto** [comment]
@Marvizm are you still working on benchmarks and rankings?

**Comment by Marvizm** [comment]
@bguzryanto not even started, I haven't seen the working api for this

**Comment by howardchung** [comment]
rankings/benchmarks APIs are deployed to production

**Comment by bguzryanto** [comment]
Thank you, I really busy this week, hope I can start this week

**Comment by howardchung** [comment]
Updated:
* Match pages still need implementation of most tables.  Framework is set up to allow accessing match object from components.  About 20% done overall
* Player pages about 50% done
* Initial implementation of filtering done
* Search done, but might want to move search field into top bar since we have a lot of space there?

Still need:
* Request page
* Heroes pages (rankings/benchmarks)
* Distributions page
* Tooltips for items/abilities

**Comment by bguzryanto** [comment]
Sure! I can move search field to the top bar.

**Comment by howardchung** [comment]
Update:

* Rankings/benchmarks are done (thanks @bguzryanto !)
* Search bar moved to top
* Request page done
* Distributions page mostly done (country MMR data needs to be put in table)

TODO:
* Match pages (some progress, but still need most tables)
* Player pages (about 5-6 tabs left to implement)
* Collapse/wrap nav on mobile (currently, it just runs off the screen)

Hopefully we'll be ready for beta in 4-6 weeks.

**Comment by howardchung** [comment]
Opened separate issues for remaining work items.  Target for MVP is October 31.

See https://github.com/odota/ui/issues?q=is%3Aopen+is%3Aissue+milestone%3AMVP
