### ISSUE TITLE
match page fixes

### ISSUE THREAD

**Issue by howardchung** [odota/ui#325]
- [ ] "Building map" should be capitalized
- [ ] ~~slightly smaller inflictorwithvalue~~
- [x] teamfights inflictorwithvalue shows index instead of number of uses

**Comment by pvskarthikeya** [comment]
Hey! I am new to this project, but want to work on this. Is that okay?

**Comment by howardchung** [comment]
Sure.  All of the above should be fairly simple fixes.  Join our Discord (linked on README) if you'd like some real-time support

**Comment by pvskarthikeya** [comment]
@howardchung Okay.

**Comment by blukai** [comment]
> teamfights inflictorwithvalue shows index instead of number of uses

fixed in https://github.com/odota/ui/pull/319/commits/251af872e8ef9d880e3aac985048c32c67bd5bc2
