### ISSUE TITLE
Missing/incorrect ability images

### ISSUE THREAD

**Issue by howardchung** [odota/ui#344]
Continuation of https://github.com/odota/core/issues/807
- [x] Invoker lvl25 (no ability icon, shows up as ability_id)
- [ ] doom infernal blade http://cdn.dota2.com/apps/dota2/images/abilities/doom_bringer_infernal_blade_md.png
- [x] riki tricks of the trade
- [x] faceless void backtrack
- [x] death prophet witchcraft
- [ ] beastmaster ability 5580 (boar)

**Comment by blukai** [comment]
> Invoker lvl25 (no ability icon, shows up as ability_id)

Was fixed here https://github.com/odota/ui/blob/master/src/components/Match/matchColumns.jsx#L189
Invoker's lvl25 ability_id = invoker_attribute_bonus while others ability_id = attribute_bonus

**Comment by howardchung** [comment]
Do you have an invoker lvl25 match to confirm?

**Comment by howardchung** [comment]
Actually, for now we don't even display stat upgrades so i guess the point is moot.

**Comment by blukai** [comment]
@howardchung http://beta.opendota.com/matches/2730850157

**Comment by souravmondal93** [comment]
Can I work on this?

I also noticed that Necronomicon ability icons are missing.
Link: https://www.opendota.com/matches/3346652500/combat
Image: http://prntscr.com/g2yq0j

**Comment by howardchung** [comment]
Sure, feel free to add those images.

**Comment by souravmondal93** [comment]
How should I approach this problem? Should I do it as we did it in https://github.com/odota/ui/pull/1097 issue?

**Comment by howardchung** [comment]
Yes, that should work.

**Comment by howardchung** [comment]
I think all of these are fixed

**Comment by souravmondal93** [comment]
Yep, I have add the listed missing icons. If any more such issues arrive, I will be happy to fix them.
