### ISSUE TITLE
Match details tabs overlap

### ISSUE THREAD

**Issue by coreymaher** [odota/ui#358]
The benchmarks and performances tabs are overlapping.

![screen shot 2016-10-28 at 3 39 54 pm](https://cloud.githubusercontent.com/assets/100885/19819919/d936abb8-9d24-11e6-9e52-b2d32467047a.png)
http://beta.opendota.com/matches/2739007618

Browser: Chrome
OS: macOS 10.12.1
Screen size: 1440 x 900

**Comment by howardchung** [comment]
I can't seem to repro this with Chrome on Windows, but I can make the font smaller globally?
