### ISSUE TITLE
localization/translation

### ISSUE THREAD

**Issue by howardchung** [odota/ui#37]
- [ ] go through the SPA and move any strings into language files
- [ ] figure out routing/persistence of language settings
- [ ] figure out how to load/update valve data in multiple languages
- [ ] have volunteer translators translate strings

**Comment by howardchung** [comment]
The current design involves having a JSON file with text strings for each language (`en.json`, `ru.json`, etc.).  Currently we import `lang/en` into the components, but I think we'll need to refactor that into a general language component that exports the appropriate language strings based on user selection (perhaps persist language selection to a cookie).

Unfortunately this will not work well for SEO, but the standard model of having a subdomain for each language won't work well with the SPA.

**Comment by dartharaknus** [comment]
@howardchung Can you update the status on this issue?

**Comment by howardchung** [comment]
* Extracting strings: Mostly done but there might be a few random spots with hardcoded strings.  I didn't enforce this during the early stages.
* Need to build the LanguageSelector component that presents a selector and saves the chosen option to local storage.
* Ability/item data from Valve is available in multiple languages, but we probably need to move to fetching it from API #338 to avoid bundling megabytes of data into the JS bundle.
* Translation: @albertcui set up https://translate.opendota.com, and we'll mention it in our release post.

**Comment by blukai** [comment]
I guess we should put the link in footer "Help translate" or smth.

**Comment by howardchung** [comment]
Sure, we can have a translate link.

**Comment by dartharaknus** [comment]
Can you make them into separate issues and let's close this.

**Comment by howardchung** [comment]
Done for 1 and 2.  3 is basically #338 and 4 is done automatically as users submit translations on crowdin.  When we add English strings to en.json, it also automatically puts them up for translation.
