### ISSUE TITLE
If metadata acc id equals acc id in match table => highlight table row

### ISSUE THREAD

**Issue by blukai** [odota/ui#373]
Like this, but probably with other color or maybe inset shadow

![image](https://cloud.githubusercontent.com/assets/20866892/19837841/2f006d8e-9ecb-11e6-94bb-4e29426df98f.png)

@howardchung What do u think about it?

**Comment by howardchung** [comment]
In general, I've avoided doing login-specific stuff (with the exception of stuff like the AccountWidget where it has to be there).   This is because testing is kind of a pain

**Comment by howardchung** [comment]
Don't think we're planning to do this, but feel free to reopen if we want to reconsider
