### ISSUE TITLE
Bad tooltips on matches for player

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#383]
When I select matches page for a player and then paginate it once or twice, I keep getting the followin tooltip issue:

![opendota](https://cloud.githubusercontent.com/assets/5713044/19912500/43228546-a09b-11e6-82c1-c7c4be582ea7.png)

Google chrome, Windows 10. Also, Safari on Mac.

**Comment by blukai** [comment]
This may be fixed in https://github.com/odota/ui/pull/389/commits/50689655bbed57cc764bba5afe6c14bd488a4bec #389

**Comment by howardchung** [comment]
Can we get a confirmation if this is fixed?

**Comment by dartharaknus** [comment]
Yes
