### ISSUE TITLE
make player wardmap responsive

### ISSUE THREAD

**Issue by howardchung** [odota/ui#390]
player page wardmaps should scale to the size of the screen, as given in redux-responsive.

**Comment by micaelbergeron** [comment]
Let's wait for #469

**Comment by howardchung** [comment]
This actually refers to player page wardmaps

**Comment by souravmondal93** [comment]
@howardchung 
I followed `VisionMap.jsx` and tried to modify `Heatmap.jsx` file to achieve the desired result of responsive, but it didn't work. Two maps were displayed side-by-side and heat-map data on the map was also lost.
Result: http://prntscr.com/g31afa

I would like to work on this issue. Any help for this task from your side will be much appreciated. :)

Thanks

**Comment by howardchung** [comment]
Looks like there's already a PR out for this issue.  Feel free to check out the code if you want to see the implementation (or jump in the code review)
