### ISSUE TITLE
Tower "deny" looks like a "last hit"

### ISSUE THREAD

**Issue by blukai** [odota/ui#401]
link: https://beta.opendota.com/matches/2753981817

![image](https://cloud.githubusercontent.com/assets/20866892/20002699/c9e4a096-a28a-11e6-9959-8cd004b25223.png)

**Comment by howardchung** [comment]
IMO this isn't necessarily wrong, it's still a last hit :)

**Comment by blukai** [comment]
Yes. but it should be specified like a deny. It's easy to fix. 🦄
