### ISSUE TITLE
Lane information on match row

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#406]

**Comment by howardchung** [comment]
This data is available in player_caches:
https://api.opendota.com/api/players/88367253/matches?limit=20&project=lane_role&project=lane

lane_role is safe/off/mid/jungle and lane is top/mid/bot/radiantjungle/direjungle

**Comment by howardchung** [comment]
Also pretty easy if someone wants to take a crack at this

**Comment by victorshao** [comment]
Hi, prospective contributor here. I could get the lane information to show on the matches page, but not the overview. I'm not sure there's an easy way to do it since the recentMatches endpoint doesn't seem to provide lane information. Is that ok?

**Comment by howardchung** [comment]
Think it just needs to be added to the database query:
https://github.com/odota/core/blob/master/routes/spec.js#L1204

**Comment by victorshao** [comment]
How's this?

![image](https://cloud.githubusercontent.com/assets/6968694/26291579/3f85a226-3e7d-11e7-8872-b1ee81f03cef.png)

Featuring bug where '>' gets cut off when the hero is Legion Commander

**Comment by howardchung** [comment]
Maybe separate the sections with `/` like the mode/lobby.

Not sure about the cutoff, probably just needs a style tweak @blukai

**Comment by victorshao** [comment]
I overlooked roamers, so that's in now. @howardchung could I trouble you again to update the recentMatches database query to include the is_roaming field? 

![image](https://cloud.githubusercontent.com/assets/6968694/26338647/b4c9dcdc-3f4f-11e7-85a8-5bed5b1a51ad.png)

**Comment by howardchung** [comment]
added: https://github.com/odota/core/commit/2f96ccf9f8aa913a713c082ab7499272bb5d0c3a
