### ISSUE TITLE
Unfulfilled records show most recent game

### ISSUE THREAD

**Issue by coreymaher** [odota/ui#414]
Players with a record that they haven't completed yet (e.g. purchased rapier) seem to show their most recent match.

See https://www.opendota.com/players/1900588/records

**Comment by dartharaknus** [comment]
@howardchung Would this need a backend change?

**Comment by howardchung** [comment]
Don't think so:

https://api.opendota.com/api/players/1900588/records

If the match given for that record has a null value for that field, just don't display it.

**Comment by greg737** [comment]
Hi, is it alright if I work on this issue?

**Comment by howardchung** [comment]
Go for it!
