### ISSUE TITLE
Casts page Tabs need to be restyled

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#416]
The blue color is from material UI and it doesn't look good. Maybe use TabBar component written by @howardchung and @blukai

**Comment by howardchung** [comment]
The problem is that TabBar is an array of links, whereas we need the tabs component from material-ui here since we are actually putting content in the children.  We can definitely style it better though.

**Comment by dartharaknus** [comment]
I think we can modify tabbar component to support content too.
