### ISSUE TITLE
Match page: various misalignmed and scale issues

### ISSUE THREAD

**Issue by rossengeorgiev** [odota/ui#418]
![aaaaaa](https://cloud.githubusercontent.com/assets/2720787/20045196/fd5273f0-a496-11e6-953f-6f3e8c292bd9.png)

**Comment by howardchung** [comment]
browser, screen resolution?

**Comment by rossengeorgiev** [comment]
Ah my bad. Firefox 49, 1366x768, no addons

Also:
![bbbbbb](https://cloud.githubusercontent.com/assets/2720787/20045509/ab046c7c-a499-11e6-82cf-4140cafacb36.png)

And scrollbar on tab bar in Chrome/Opera:


![cccccc](https://cloud.githubusercontent.com/assets/2720787/20045526/e5dfe240-a499-11e6-8720-7071a30244be.png)

**Comment by rossengeorgiev** [comment]
Bars in the table are also misaligned

![dddd](https://cloud.githubusercontent.com/assets/2720787/20048396/288b87f6-a4b4-11e6-9009-57bab97ed850.png)

**Comment by b1acKr0se** [comment]
This is how it looks on Google Chrome 51.0.2704.103, Ubuntu 14.04, 1920x1080 display

![opendotacsserror](https://cloud.githubusercontent.com/assets/8596158/20049361/2e670da8-a4f5-11e6-9e94-ed6d113f640c.png)

**Comment by howardchung** [comment]
Thanks, I guess the problem isn't isolated to FF then.

**Comment by blukai** [comment]
Hehe, I did this. Github, why??
![image](https://cloud.githubusercontent.com/assets/20866892/20066398/1984c23e-a51a-11e6-9934-accbd362b240.png)

**Comment by rossengeorgiev** [comment]
@blukai 
![umadethis](https://cloud.githubusercontent.com/assets/2720787/20067071/abdb8e38-a50b-11e6-908f-06eb3d4d61f4.png)

**Comment by blukai** [comment]
Ok. 😆

**Comment by howardchung** [comment]
@b1acKr0se 
@rossengeorgiev 

should be deployed in a few minutes, can you confirm if the issue is fixed in 15 minutes or so?

**Comment by b1acKr0se** [comment]
@howardchung 
The KDA bar is still misaligned.

![opendota2](https://cloud.githubusercontent.com/assets/8596158/20086383/5aac81c4-a5a2-11e6-9dc5-36cae4ed63f0.png)

**Comment by howardchung** [comment]
It looks fine in that screenshot (but offset in the one you posted before).  Fixed?

**Comment by b1acKr0se** [comment]
@howardchung The red bar is still a bit higher than the other two. Is it just me?

**Comment by howardchung** [comment]
My eyes are hurting from squinting at the screenshot.  I THINK it's just an optical illusion, though?  If I lean in close it seems to go away.

**Comment by dartharaknus** [comment]
Yes, it's an optical illusion.

**Comment by b1acKr0se** [comment]
@howardchung @dartharaknus Okay then, but even if this is just an optical illusion, any plan to somehow get rid of it (by changing the color maybe?) ? I personally don't mind though.

**Comment by howardchung** [comment]
let's see what @blukai thinks, maybe a color shift or offsetting the bar from the bottom of the row would do the trick?

**Comment by dartharaknus** [comment]
Red color is fucking strange. If you have red text on a black background, it looks like it's glowing. Even though there is no glowing thing which is specifically added.

**Comment by b1acKr0se** [comment]
This is also the case with Dotabuff, however their bars are shorter and the color position shift makes it hardly noticeable.

**Comment by rossengeorgiev** [comment]
@howardchung looks like everything is fine. The bar is definitely aligned, you can check by zooming on windows with `winkey -/+`
