### ISSUE TITLE
The title is always the same

### ISSUE THREAD

**Issue by evaryont** [odota/ui#422]
I can't determine what page is what in my history, of if I have multiple tabs open, or any other situation when a opendota tab is opened in the background. The title is always "OpenDota". It gets set in the [original HTML](https://github.com/odota/ui/blob/master/index.html#L6) and I don't see it changed anywhere else.

**Comment by howardchung** [comment]
I think the solution is to use JS to set window.title dynamically: `document.title = "Match X"`.  Not sure if there's a more React way to do this.

**Comment by dartharaknus** [comment]
@mike-robertson can look into this, I guess.

**Comment by andrkrn** [comment]
I think you guys can use this. https://github.com/gaearon/react-document-title

**Comment by bguzryanto** [comment]
@andrkrn react-document-title is not actively maintained, the author busy to maintain CRA and react fiber. 

@howardchung There is a way to do this with [react-helmet](https://github.com/nfl/react-helmet) it's support defining meta tags, script tags, title, base etc.
