### ISSUE TITLE
Translation: string templating, plurals and so on

### ISSUE THREAD

**Issue by rossengeorgiev** [odota/ui#423]
Hello,
I've see a bunch of examples where a sentence is split into smaller parts and there is some dynamic value in between. 

An example of this are `time_` strings. I assume this ends up as `2 [hours][s] 5 [minutes][s] [ago]`. For Bulgarian, the `ago` should be in front while the words for hours and minutes have different endings for their plural form. Needless to say, this will be a problem in other languages.

One way to do it would be to have a string for plural and one for singular and finally a template `{hours} {minutes} {seconds} ago`. Or you could have a template for all possible combination. Valve does that sometimes. There are lots of other examples where a sentence is split up and would make translation difficult to impossible.

**Comment by howardchung** [comment]
Yeah, I was worried about this.  We can put template strings in the string file perhaps, or bring in a library like https://github.com/yahoo/react-intl

**Comment by rossengeorgiev** [comment]
I can't offer any suggestion as I'm not familiar with React and it's ecosystem. I imagine there would be a library that solves the problem elegantly.

**Comment by howardchung** [comment]
Does "${Dire Mid Ranged} ${Barracks}" exhibit this same problem?

If it does, I suppose the solution would be to have a separate string defined for barracks and tower

**Comment by rossengeorgiev** [comment]
Those combinations can be problematic depending on language. It makes sense to do programmatically in order to reuse stuff, but problematic. Valve simply adds a string-token for each permutation. There is also a lot of duplication for some same thing used in different places. I think that makes sense, because it forces programmers to write simple code, and then any translation details can be solved by just changing the tokens.
