### ISSUE TITLE
Separated tables by team 

### ISSUE THREAD

**Issue by kozhilya** [odota/ui#431]
Tables on match page, which were separated to 2 different tables by team (eg. "Damage" on "Combat" tab or "Benchmarks") looks like not binded, and it's very strange. At the same time, some other tables have opposite problem: there is no posibility to separate players by teams when it obviously needed (eg. "Vision").

Isn't it better not to separate this tables but to mark rows with radiant/dire icon left to hero icon?

**Comment by howardchung** [comment]
merge with #404 

We should decide if we want to:
* Live with occasionally misaligned tables
* Figure out how to keep them separate, but force the column widths to equal
* Recombine the tables
