### ISSUE TITLE
Declension of cardinal numerals issue for russian

### ISSUE THREAD

**Issue by kozhilya** [odota/ui#433]
In other language there is problems to. Eg. in russian there is no problem with "ago", but the declension problem is very strong. Just because the phrases in Russian formed otherwise, for this type of entry is required to specify three forms of the word, which are used for some rule requires some comparison operations.
More details can be found in the [Wikipedia](https://en.wikipedia.org/wiki/Russian_declension#Declension_of_cardinal_numerals), 4th paragraph.

For now, i leave only reductions of this words in russian ("сек.", "ч.") on translation page. However, if you want to fix this issue, here the proper JS-solution for russian language (AIK, function body syntax is compatible to React): https://gist.github.com/realmyst/1262561 - but i'm not sure that it's necessary for other language. It looks like that it's the unique russian issue...

**Comment by howardchung** [comment]
Yep, I think @rossengeorgiev reported a similar issue with Bulgarian.  We'll need to implement a solution for this, maybe need to add separate language blocks for the fromNow function.

**Comment by howardchung** [comment]
Would the following be sufficient?

http://momentjs.com/docs/#/customization/relative-time/

Basically, defining a template string for "ago" (to handle word order), then a separate string for singular and plural for each time unit.

**Comment by howardchung** [comment]
@kozhilya can you confirm if having one string for singular time units and one for plural will work?

(e.g.):
```
"time_ago": "%s ago",
"time_s": "second",
"time_ss": "seconds"
```
