### ISSUE TITLE
Teamfights page Tabs need to fix width

### ISSUE THREAD

**Issue by roman-kosov** [odota/ui#434]
Example:
over 18 fights in game
https://www.opendota.com/matches/2741286001/teamfights

Monitor is 1440px:
![Teamfights fullscreen](https://cloud.githubusercontent.com/assets/11503318/20058366/021c4a9e-a534-11e6-8344-d8947c7d7859.png)

Solution:
– 2 row and more
– Dropdown Menu

**Comment by howardchung** [comment]
I'm thinking a dropdown menu selector might scale better.  It also avoid the issue right now of rendering every teamfight at once (which is slow on mobile)

**Comment by roman-kosov** [comment]
> which is slow on mobile
Safari from MacOS slow too.

**Comment by dartharaknus** [comment]
Related to #415
