### ISSUE TITLE
Cross Origin Problems in development

### ISSUE THREAD

**Issue by lucidlemon** [odota/ui#435]
just tried to contribute a bit by forking the project and working on it locally, when I wanted to visit a "deeper" site like `http://localhost:8080/heroes/1` I noticed that you guys set the cross site scripting settings wrong:

```
Fetch API cannot load https://api.opendota.com/api/rankings?hero_id=1. The 'Access-Control-Allow-Origin' header contains multiple values 'http://evil.com/, *', but only one is allowed. Origin 'http://localhost:8080' is therefore not allowed access. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Chrome Canary Version 56.0.2912.0 canary (64-bit)

**Comment by howardchung** [comment]
This line sends back the origin header as the CORS domain.
https://github.com/odota/core/blob/master/routes/api.js#L14

Check your origin header, does it contain the compound string `http://evil.com/, *`?

I see you submitted pull requests--were you able to get it to work?

We can avoid this issue by not setting `{credentials: true}` except for the one endpoint that requires it: `/api/metadata`

**Comment by howardchung** [comment]
I think this is the same issue as #482 , and think I have a fix for it
