### ISSUE TITLE
Cosmetics page need to fix HTTPS-requests to cdn.dota2.com

### ISSUE THREAD

**Issue by roman-kosov** [odota/ui#436]
**Problem:**
Cosmetics page was allowed to display insecure content from cdn.dota2.com:
HTTPS...
HTTPS...
HTTPS...
HTTPS...
HTTPS...
HTTP...... 
![HTTPS vs HTTP request](https://cloud.githubusercontent.com/assets/11503318/20060482/b4b66cfc-a53e-11e6-82c2-a05e35a26ee7.png)

**Example:**
https://www.opendota.com/matches/2761811730/cosmetics

**Comment by howardchung** [comment]
Nah, keep this open, we should fix it.  It just require a change to odota/core too.

**Comment by roman-kosov** [comment]
https://github.com/odota/core/issues/1309:
> See `web.js` section where we proxy hero/item/ability images. Need to do the same with the image base path.

 **`web.js`**:
https://github.com/odota/core/blob/master/svc/web.js#L59

**Comment by howardchung** [comment]
Core change is made
