### ISSUE TITLE
SEO Solution

### ISSUE THREAD

**Issue by erayarslan** [odota/ui#449]
Whats your SEO Solution for Single-Page Architecture guys?

**Comment by howardchung** [comment]
I think Google runs Javascript now. Aside from that we don't really have one.  I guess we could put some keywords into the base HTML?

**Comment by erayarslan** [comment]
Google still cannot compile JavaScript sources for your html source. But opendota.com's old indexes still in Google Store. And opendota still usin' same url's. But this cannot work for soon. Probably opendota's indexes will be erased.

u can check with "fetch as google"

google bots think like "oh all urls has same duplicate content!" (404 redirection trick page or your index.html whatever)

"oh that site has just a two different page :/"

u know. :(

**Comment by howardchung** [comment]
7 on google for "dota 2 stats":
https://www.google.com/#q=dota+2+stats

2 on google for "dota 2 data":
https://www.google.com/#q=dota+2+data

I think this could be improved.  I've tended to avoid the term "stats" in favor of "data" since we are not statisticians, but maybe in the interest of SEO we can put some keywords in the meta tags/title?

**Comment by howardchung** [comment]
In addition, searches for player profiles like "Arteezy opendota" should come back with the correct result.  This is a combination of rendering the official player name into the page, and putting it into the title: #422

**Comment by erayarslan** [comment]
u guys still manipulating dom with js.
google cannot handle for seo. :/

i think u guys need pre-render solution like [prerender.io](https://prerender.io/) or [example phantomjs seo server](https://github.com/sausozluk/530)

**Comment by howardchung** [comment]
Google does run the JS--we know this because the result contains strings such as "Login for replay parsing" that aren't present in the HTML template.

**Comment by erayarslan** [comment]
are you sure?
u must check with "fetch as google" and
i think "opendota" still have old indexes.

**Comment by howardchung** [comment]
Yeah, some of the results are outdated.  Is there a method to force google to rebuild its index?

**Comment by erayarslan** [comment]
clean all indexes and wait google bots :( "very risky"
cause i didnt believe "google does run js" thing.

u must look with "[fetch as google](https://www.google.com/webmasters/tools/googlebot-fetch)"

**Comment by howardchung** [comment]
Looks like the JS runs fine, so the homepage is okay, but pages that aren't the home page may not be indexed properly.  Right we we utilize the GitHub pages 404 custom page to redirect the user to index.html, and store the path in local storage so we can put it back after the redirect.

**Comment by erayarslan** [comment]
if google can handle js changes 404 redirect trick not a problem.

**Comment by howardchung** [comment]
We seem to have improved to number 2 for "dota 2 stats" and number 1 for "dota 2 data" so seems like Google indexing is working fine.  

What doesn't work very well yet is trying to google search for particular players/tournaments/heroes/etc.

https://www.google.com/#q=dendi+opendota doesn't work very well, for example

**Comment by howardchung** [comment]
While it would be nice to be able to direct link to a player page from google, the first result is already the opendota home page, which has a handy search box.  Dendi is only a few keystrokes away.  If there's interest or demand for this, we can look at it again.
