### ISSUE TITLE
Error when accessing using HTTP instead of HTTPS

### ISSUE THREAD

**Issue by OpenDotaUser** [odota/ui#453]
At work the site **https**://www.opendota.com/ is blocked and if I try using **http**://www.opendota.com/ instead, I have access to the site, but the site do not display any data, everything is broken.

Search feature returns 0 results always
Request parse throws an error
Heroes page does not display the images of the heroes
Distributions page does not return any data

**Comment by blukai** [comment]
Replacing https://github.com/odota/ui/blob/b80e371a28aa8c46d6e8ebeebdd953930b868ae4/webpack.config.js#L77 from `https://api.opendota.com` to `//api.opendota.com` should work

**Comment by coreymaher** [comment]
Do we want it to work over http?

**Comment by blukai** [comment]
`//` means that requests will be addicted to protocol that user using.

**Comment by howardchung** [comment]
Note: I undid this change since I enabled force HTTPS on cloudflare.

@OpenDotaUser does this prevent you from using the site completely?
