### ISSUE TITLE
Unexpected stun duration

### ISSUE THREAD

**Issue by coreymaher** [odota/ui#458]
The match https://www.opendota.com/matches/2765996319 shows the Razor having 14.75 seconds of stun: https://www.opendota.com/matches/2765996319/performances
This is odd since the Razor did not cast any stuns abilities: https://www.opendota.com/matches/2765996319/casts

There's a few possible reasons I can think of:
1. The stuns column is not label correctly and is showing debuffs (from unstable current?) instead of only stuns
2. The enemy had a lotus orb. I'm not sure if it is possible or happened, but maybe they used it on Razor and then stunned themselves.

**Comment by coreymaher** [comment]
I think we should probably just close this out since it's pretty old. If I find another example I can create a new issue.

**Comment by howardchung** [comment]
ok, closing
