### ISSUE TITLE
Number rounding issue in graph y-axis

### ISSUE THREAD

**Issue by howardchung** [odota/ui#459]
From reddit:

1: https://www.opendota.com/players/349232998/trends/purchase_tpscroll Not all values on Y axis are not rounded

2: lasthits on objectives made by player's illusions are attributed to them on overview/buildings map, but are attributed to Anonymous on log pages

https://www.opendota.com/matches/2766655835/overview If you look at buildings map, radiant top barracks, Morphling got last hit on both of them However, since it was done by illusions, rax are attributed to Anonymous on the log page (https://www.opendota.com/matches/2766655835/log 44:44 44:48) Same thing for Naga's illusions and bottom ranged rax

**Comment by blukai** [comment]
Building map take values from `player.damage` and `player.killed` meanwhile log - from `objectives`

**Comment by howardchung** [comment]
Yeah, objectives contains data from the CHAT_MESSAGE* events, which are the messages that show up on the left in-game.  Unless we merge data across log events, we can't link them directly.

We should do something about the first though.  Not sure what's causing it
