### ISSUE TITLE
Permanently asks to login, even though already logged in

### ISSUE THREAD

**Issue by NewAmbition** [odota/ui#474]
- **OS**:
- **Screen Resolution**:
- **Browser/Version**:
- **Link to page with the issue, or screenshot**:

**Comment by howardchung** [comment]
Can you try clearing your cookies and logging in again?

**Comment by NewAmbition** [comment]
Unfortunately it does not resolve the issue.

Every time I got to https://www.opendota.com/ or https://www.yasp.co it takes me to the same login page

**Comment by howardchung** [comment]
The home page is always the same regardless of login state.  The way to tell if you are logged in is it you see a profile and logout link in the top right.

**Comment by NewAmbition** [comment]
Makes sense, just a bit ambiguous to be taken to a page which tells me I should log in to see things
