### ISSUE TITLE
Remove inline eslint rules for globals

### ISSUE THREAD

**Issue by micaelbergeron** [odota/ui#476]
Following the change of .eslintrc.json in #469, we should remove all the inline eslint rules for the global variables.

```
/* globals API_HOST */ 
```

Additional variables shall be added to the eslintrc down the road.

**Comment by howardchung** [comment]
Actually, my IDE (cloud9) uses this in order not to show warnings for undefined variables.  Since it's just a comment it can't hurt, so let's just keep doing this.
