### ISSUE TITLE
Kill data under combat tab is erroneous in match 2778035301

### ISSUE THREAD

**Issue by ArandomB** [odota/ui#485]
Pudge has 3 deaths and Omni 0 deaths in overview correctly. In the combat tab, Omni is shown having 1 death from slark while Pudge is shown having 2 deaths overall.

**Comment by howardchung** [comment]
Aegis deaths/last hit by tower/creep?  Unfortunately the combat log data doesn't sync up properly with the scoreboard:

https://github.com/odota/core/issues/726
