### ISSUE TITLE
Hidden mmr is not changing from past 15 games.

### ISSUE THREAD

**Issue by batrabhinav** [odota/ui#497]
Hidden mmr is not changing from past 10-15 games.
It's stuck on a particular number and standard deviation.
What should be done about it>?

**Comment by howardchung** [comment]
Please note that this is NOT hidden MMR (as in unranked MMR that valve uses).  It's an estimate of your MMR based on visible data from players in your games.

It will not change if there are no players in a match sharing MMR data.
