### ISSUE TITLE
Change hero images to hero icons in building map tooltips

### ISSUE THREAD

**Issue by blukai** [odota/ui#498]
https://github.com/odota/ui/blob/master/src/components/Match/BuildingMap/BuildingMap.jsx#L135

**Comment by covertPZ** [comment]
This will probably be easier by making a change to the [dotaconstants](https://github.com/odota/dotaconstants) file to include the link to the hero icons as well. A string replace from `<hero>_full.png` to `<hero>_icon.png` works if we really don't want to change that lib though.

**Comment by howardchung** [comment]
I'm fine with either fix

**Comment by covertPZ** [comment]
I think the change to the constants would be more appropriate, especially if we want to do something in the future with player icons elsewhere. I can make a pull request against that repo and then start working on the styling with the icons.

**Comment by covertPZ** [comment]
Pull request [#9](https://github.com/odota/dotaconstants/pull/9) submitted against the dotaconstants repo.

**Comment by howardchung** [comment]
published
