### ISSUE TITLE
MMR history too old

### ISSUE THREAD

**Issue by hhoanganh** [odota/ui#503]
My MMR tab shows from Jun 23 to Aug 28, why it doesn't update to today ?

- **OS**:
- **Screen Resolution**:
- **Browser/Version**:
- **Link to page with the issue, or screenshot**:

**Comment by howardchung** [comment]
Are you displaying it in your profile?

**Comment by hhoanganh** [comment]
I didn't show MMR on ingame profile, 30 mins ago i editted to show MMR, relogin OpenDota but still not see it update. Should i wait for more time ?

**Comment by blukai** [comment]
You should show mmr in profile and then play ranked game.
