### ISSUE TITLE
Don't show MMR of players that have hidden it since X days

### ISSUE THREAD

**Issue by BlessSource** [odota/ui#513]
I'm 6.1k right now but my profile shows that i'm still 5.2k from like a year ago. Or let people hide it in the options just like dotabuff

**Comment by blukai** [comment]
https://github.com/odota/ui/issues/503#issuecomment-261111739

@howardchung I guess we should make tooltip or something with explanation for situations like this and/or probably create a button that updates mmr without necessity to play a game 🦄

**Comment by howardchung** [comment]
This might be a little difficult.  The mmr is fetched from a Redis zset for seed, but that lets us only store a key and a score, which are account id and mmr.  We can't store metadata like how old it is, and we also can't expire individual elements in the zset.

We'd either have to do a database lookup on each request which comes with a performance hit, or store each mmr data point in a separate redis key which is less efficient space wise.

**Comment by BlessSource** [comment]
Then just add the option to hide it maybe.

**Comment by BlessSource** [comment]
Then just add the option to hide it maybe.

**Comment by howardchung** [comment]
I think the best solution for this is #1183 (showing how old the data is).  The user can then place the data in the correct context.
