### ISSUE TITLE
proMatches/proPlayers listing

### ISSUE THREAD

**Issue by howardchung** [odota/ui#514]
After merge of https://github.com/odota/core/pull/1362

Add two new top-level tabs showing a list of recent pro matches and a list of pro players, for easy access

**Comment by howardchung** [comment]
I think it would be nice to have this in before the Boston major

**Comment by mike-robertson** [comment]
Does anyone think this should go on the front page as well?

**Comment by blukai** [comment]
Maybe better make section called e-sports like dotabuff does and put drop-down list with pro players, pro matches into navbar?
I think in future we can give users an option to follow teams, leagues, players and make feed of this data on the front page. It will require some backend changes.

**Comment by howardchung** [comment]
I was thinking separate navbar entries for tabs called "Matches" and "Players".

**Comment by howardchung** [comment]
I think the proPlayers part of this can be satisfied by #575 .  Users will likely try to enter a pro's name into the search.
