### ISSUE TITLE
Progress bar indicators are removed in new UI

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#515]
> The "progress bar" style indicators have been removed from underneath everything but rate stats, which makes the data harder to compare at a glance, especially since the tables are wider and the text is smaller. I'd recommend putting these back on "Actions," "Performances," and "Farm," at a minimum.

They kinda looked ugly to me. So, maybe we want display them a bit differently instead of progress bars so that a single glance can give a lot more information.

**Comment by howardchung** [comment]
This is related to #86 , we should add support to the Table component that will handle this.

**Comment by dartharaknus** [comment]
Yeah, but I don't think it's good UI. We should find another way to display this which looks better.

**Comment by howardchung** [comment]
merge into #86
