### ISSUE TITLE
This match page never loads

### ISSUE THREAD

**Issue by fireattack** [odota/ui#517]
https://www.opendota.com/matches/2788035196

**Comment by howardchung** [comment]
@blukai this match doesn't seem to have a first blood logged in objectives.  I fixed it, but we might want to restructure the code better to handle this case?

**Comment by fireattack** [comment]
Thanks! BTW just curious, did you fix it by find a better way to log "first blood" correctly (Because obviously there should be a FB in this game) or just ignore/bypass FB when it is not logged correctly?

**Comment by howardchung** [comment]
I just set a default value for objective first blood to 0.  If this value deviates too far from the match.first_blood_time property, we just skip rendering the timeline since something is wrong with the data.

**Comment by fireattack** [comment]
That makes sense. But there should be a more fundamental problem that why the FB data is not there right?

**Comment by howardchung** [comment]
It's likely a problem with the replay, would have to run it through the parser and manually inspect to output to debug the issue.
