### ISSUE TITLE
Add CSS linter

### ISSUE THREAD

**Issue by pksunkara** [odota/ui#530]
The current css code is not really styled well. We should have a linter to format it properly.

**Comment by howardchung** [comment]
@mike-robertson any ideas how to do this?  Does eslint have some kind of plugin for css?

**Comment by gu3st** [comment]
@howardchung there's csslint. Not sure if that's the route we'd wanna go down (or if there's other options that are more suitable)

**Comment by howardchung** [comment]
If it:
* can be installed with npm
* can be easily added to CI
* isn't too heavyweight

I'm ok with it :)

**Comment by blukai** [comment]
How about stylelint.io ❓

**Comment by mike-robertson** [comment]
I agree, I think stylelint is the best one from what I have seen. I don't have a lot of experience with css linters though.

**Comment by mike-robertson** [comment]
I can set this up
