### ISSUE TITLE
My account have no desplayed stats in open dota

### ISSUE THREAD

**Issue by uplinkcable2** [odota/ui#534]
- **OS**:
- **Screen Resolution**:
- **Browser/Version**:
- **Link to page with the issue, or screenshot**:

**Comment by howardchung** [comment]
Need more information, like a link to the player profile

**Comment by howardchung** [comment]
Likely this is due to not having public match data exposed.  Enable the setting in your Dota client, then click the refresh button on your player profile.  Feel free to comment/reopen if you have further difficulties.
