### ISSUE TITLE
show radiant/dire team name if available

### ISSUE THREAD

**Issue by howardchung** [odota/ui#538]

**Comment by covertPZ** [comment]
Is this looking to be put in place of "Radiant" and "Dire" on all of the pages or in addition to it?
Maybe we want to just use team tags?
ie. Radiant (EG) Overview

**Comment by howardchung** [comment]
I think the original intent was to replace Radiant/Dire with the full team name, @blukai can confirm.

**Comment by howardchung** [comment]
Moving to December
