### ISSUE TITLE
Whoops! Something went wrong! 

### ISSUE THREAD

**Issue by blissfreak** [odota/ui#544]
Whenever I try to login to ODota this keeps happening 

OS is Windows 10, reso 1920x1080 and the latest chrome version for browser..
![od](https://cloud.githubusercontent.com/assets/24191863/20641500/246d8dfc-b41f-11e6-8ed7-68caf17692cc.JPG)

**Comment by howardchung** [comment]
Can you open your browser console (ctrl+shift+J) and open the network tab?  What do the network requests say?

I checked the server side API response for the account ID and it looks ok:
http://api.opendota.com/api/players/308140891

**Comment by blissfreak** [comment]
Thanks for replying, opened it and idk what to make of it so here it is.
![wqwq](https://cloud.githubusercontent.com/assets/24191863/20641543/5dcb0ab0-b420-11e6-8fde-3ee77be90a6e.JPG)

**Comment by howardchung** [comment]
Can you click the "XHR" so it filters to only the data requests?

**Comment by blissfreak** [comment]
Had to refresh the page coz i tabbed out once :3
![od2](https://cloud.githubusercontent.com/assets/24191863/20641582/0388e1fc-b421-11e6-972b-786d69b2da93.JPG)

**Comment by howardchung** [comment]
Can you click on one of the ones that say "403"?

**Comment by blissfreak** [comment]
![od3](https://cloud.githubusercontent.com/assets/24191863/20641639/3ca93d78-b422-11e6-8c61-3ce5009d07a9.JPG)
Welp...

**Comment by howardchung** [comment]
Has it ever worked for you or is this a recent problem?

Could I also see the headers?

**Comment by blissfreak** [comment]
![od4](https://cloud.githubusercontent.com/assets/24191863/20641645/7855d430-b422-11e6-8eca-980192131f4e.JPG)
This is the first time im trying it since yasp was changed to opendota. It worked fine when it was Yasp

**Comment by howardchung** [comment]
Are there any errors in the console?

**Comment by blissfreak** [comment]
![od5](https://cloud.githubusercontent.com/assets/24191863/20641675/1e88a6fc-b423-11e6-9265-e3ade9673f94.JPG)
This is the whole console. Lots of red so lots of errors i guess.

**Comment by howardchung** [comment]
Yeah this seems to be the same issue as https://github.com/odota/ui/issues/482

I haven't been able to track down the exact cause yet.

To confirm, this link works when you open it directly?
http://api.opendota.com/api/players/308140891

**Comment by blissfreak** [comment]
![od6](https://cloud.githubusercontent.com/assets/24191863/20641696/ceab6736-b423-11e6-80a1-ec9d2a9967e4.JPG)
I get this so I think it works I guess

**Comment by blissfreak** [comment]
Yep passed all.
Thanks for your help anyways :)

**Comment by howardchung** [comment]
Actually, try this one:
https://resttesttest.com/

Click "ajax request" and does it succeed?

**Comment by blissfreak** [comment]
Yeah I get "HTTP 200 OK" so it succeeded I think.

**Comment by howardchung** [comment]
OK, it seems that it'll work if we pass a specific domain instead of a wildcard.  I suppose I can go back to attempting to return the passed origin.  I'll try that out later today and make a note here so you can check again.

**Comment by blissfreak** [comment]
thank you :)

**Comment by howardchung** [comment]
Give it another try?

**Comment by blissfreak** [comment]
Nope, still can't view it sorry

**Comment by howardchung** [comment]
Can you show me the headers for the "metadata" network request as well as one of the 403 ones?

**Comment by howardchung** [comment]
The weird thing I can't figure out is where the 403 error is coming from.

Can you visit this dev page so I can check what the server is getting?

http://hchung.westus.cloudapp.azure.com:8080/players/88367253/overview

**Comment by howardchung** [comment]
any update on this @blissfreak ?

**Comment by howardchung** [comment]
@blissfreak can you confirm if this was fixed since the cloudflare security change in #631 ?

**Comment by howardchung** [comment]
closing since i haven't heard back, but reopen if it's still an issue.
