### ISSUE TITLE
match data deletion requests

### ISSUE THREAD

**Issue by tampines999** [odota/ui#545]
as above

**Comment by howardchung** [comment]
This isn't implemented yet.  It requires a couple of things:
* User needs to be able to prove that they own the account_id in question
* Need to write scripts to remove the data from all the tables properly

**Comment by dartharaknus** [comment]
Why is this needed? We don't send any emails anyway and we won't parse your matches if you are not logging in.

**Comment by dartharaknus** [comment]
Actually, I mistakenly parsed a couple of practice matches long ago and I am wondering how I can prevent them from being associated with me.

**Comment by howardchung** [comment]
If they were lobbies and done via uploaded replay then they don't persist.

**Comment by dartharaknus** [comment]
No, they are normal matched ones, but they just didn't count (not visible in API) because of some connection issues of the server at the time.

**Comment by howardchung** [comment]
In that case the radiant_win property is probably null and we don't count the match toward aggregations

**Comment by dartharaknus** [comment]
I know, but I guess users should probably have an option to remove it from match lists of their profile.
