### ISSUE TITLE
Tells me whoops somthing is wrong

### ISSUE THREAD

**Issue by zhuozhenzhou** [odota/ui#547]
- **OS**:
- **Screen Resolution**:
- **Browser/Version**:
- **Link to page with the issue, or screenshot**:

**Comment by howardchung** [comment]
Can you open your browser console and let me know if you see 403 requests for the match/player data like in #482 and #544 ?

**Comment by howardchung** [comment]
Problem fixed?

**Comment by zhuozhenzhou** [comment]
seems to be a problem on my end.
