### ISSUE TITLE
pagination on matches page

### ISSUE THREAD

**Issue by howardchung** [odota/ui#55]
Allow pagination on player/matches page to get more pages of matches.

**Comment by mike-robertson** [comment]
How are we going to handle these api requests? Is there a way to request a specific page of results? Otherwise the only thing I can see working is requesting increasingly larger and larger datasets from the backend which means lots of wasted data over the wire.

**Comment by howardchung** [comment]
Yes, there is an offset parameter we can use to request a particular page.
Alternatively, we can load all matches to start and paginate client side.

**Comment by howardchung** [comment]
As MVP, we could just request/display all matches.  This is what the current site does (all matches, no pagination).

**Comment by howardchung** [comment]
What does the current implementation do?

**Comment by mike-robertson** [comment]
It just paginate if there are more than 20 items. It's configurable, so we can mess with that or disable it for certain tables.

**Comment by howardchung** [comment]
How does it request the additional data (for matches)?  Does it use limit/offset or load everything initially?

**Comment by howardchung** [comment]
nvm, looks like it's not applied to matches table yet.  For the heroes page where it is applied, it just extracts the appropriate set of rows from state which is loaded completely already.
