### ISSUE TITLE
Ability Draft matches no longer showing by default

### ISSUE THREAD

**Issue by davejkish** [odota/ui#554]
Hi,

On the main page (as well as the matches page) no longer show ability draft or other such modes.  Until recently, it was showing all of these and now it only shows the standard game modes.  If I know the match ID, I can search for it (and it's been parsed), but it doesn't show up by default, and the filter for "abiltiy draft" does not bring any of them up.

Images/Profile can be provided on request.

**Comment by howardchung** [comment]
Seems to be working fine for me, this should have been fixed with #548 .

Perhaps you haven't refreshed in a while?

**Comment by davejkish** [comment]
Odd, you're right. Cleared Cache and all good. Please disregard.

On Nov 30, 2016 10:56 AM, Howard Chung <notifications@github.com> wrote:

Seems to be working fine for me, this should have been fixed with #548<https://github.com/odota/ui/pull/548> .

Perhaps you haven't refreshed in a while?
