### ISSUE TITLE
Request for average XPM/GPM with peers

### ISSUE THREAD

**Issue by Crazy3lf** [odota/ui#562]
As a player who mainly play party with friends as support, I'd like to see how well me or my friends do in those game that we party together.

**Comment by howardchung** [comment]
Would you want this as an additional column on the peers page?  If so, we'll need to compute that data server side and send it over.

**Comment by Crazy3lf** [comment]
Ya, that would be great!

**Comment by howardchung** [comment]
Added this data in https://github.com/odota/core/pull/1420
