### ISSUE TITLE
"Totals" tab on player pages

### ISSUE THREAD

**Issue by opendotasucksnow** [odota/ui#564]
Why did you get rid of total count of stats on pages for a meh UI update and generic name change. You  used to be able to see total counts for stats on the records page and the total games that the stat was available for.  Now its a meh page that barely is better than the dotabuff equivalent. You also got rid of all ways to contact you other than this page, and now i feel bad using a bug report to complain about this bad update. Being able to see total stats like total kills and total last hits was cool, and filtering let you see the stats for specific heroes, good features that made your site actually better than the other dozen offerings  out there

**Comment by mike-robertson** [comment]
You can still filter any of the player pages. The button in the bottom right corner which looks like a funnel and is blue should do it. There may be a bug with the filtering in mobile, but I'm not sure about desktop. Please feel free to make a bug issue if the filter isn't working properly

**Comment by howardchung** [comment]
Since filtering is already implemented (you might have missed the button), it sounds like the main thing you're missing is the sum/n for the fields on the records page.  I didn't think this was a particularly useful feature, but maybe I'm wrong :)

**Comment by howardchung** [comment]
Might be worth adding a new endpoint/tab called "totals" that sums up data for a bunch of fields and presents them separately, e.g.
`Player X has last hit 110,234 creeps in their career`

**Comment by howardchung** [comment]
implemented in #893
