### ISSUE TITLE
Profile KDA-tab misnamed

### ISSUE THREAD

**Issue by Merloni** [odota/ui#570]
On the profile screen under histograms and trends the KDA tab is actually named KLA.

**Comment by howardchung** [comment]
This is intended, it's Kills-Lives-Assists, which is (K+A)/(D+1)

**Comment by Merloni** [comment]
makes sense, the actual url still states /kda though

**Comment by howardchung** [comment]
Yeah for legacy purposes i didn't change the internal field names.
