### ISSUE TITLE
Can we get KDA stat in records?

### ISSUE THREAD

**Issue by 12039350** [odota/ui#578]
I don't really care about KLA (But I understand some people would), so I'd like to see highest KDA.

**Comment by howardchung** [comment]
KLA is intended to be a more accurate version of KDA.  They measure the same thing and can be used for the same purpose--highest KLA = highest KDA

**Comment by 12039350** [comment]
They're not the same though. My highest KLA is 38 when I went 25-0-13 as Timbersaw. My highest KDA is 46 when I went 11-1-35 as KotL. KLA essentially adds an extra death to the stat.

**Comment by howardchung** [comment]
hmm, in that case I'd consider the 25-0-13 "better", since you did that with 1 "life", whereas the 11-1-35 used 2 "lives".  Doesn't it seem strange to make 0 and 1 death equal?
