### ISSUE TITLE
MMR History Graph not loading

### ISSUE THREAD

**Issue by JugOrNot** [odota/ui#581]
- **OS**: Windows 10
- **Screen Resolution**: 1366x768
- **Browser/Version**: Chrome / Microsoft Edge
- **Link to page with the issue, or screenshot**: http://i.imgur.com/xm1x9mZ.png

MMR Graph is not loading for me. I have addblock off. I tried using incognito mode on Chrome and Microsoft Edge but it is not loading. The loading animation is playing for a couple of seconds and then freezes. I asked someone else and told me it is loading for them. I also tried using mobile data to load the site but still not working. Other categories work fine.

**Comment by mike-robertson** [comment]
Can you open your console (right click and select inspect, then click the 'console' tab). Do you see any errors in there, and can you link a screens hot here? It may also be worth checking the network tab, then clicking on 'xhr' to filter, then clicking on any red items, then clicking on the 'preview' tab of the request. If you send a screenshot of those, it will also help.Thanks for reporting this!

**Comment by howardchung** [comment]
I see this in the MMRGraph component:
```
const MMRGraph = ({ columns }) => (
  <Graph
    type="line"
    columns={columns}
    name="Solo MMR"
    colors={{
      'Solo MMR': npmColor().rgb(102, 187, 255).rgbString(),
      'Party MMR': npmColor().rgb(255, 76, 76).rgbString(),
    }}
    noX
    hidePoints
    xAxis={getXAxis(columns)}
    otherColumnNames={[{ name: 'Party MMR', property: 'competitiveRank' }]}
  />
);
```

Do we need to update the rgbString() function call to string()?

**Comment by JugOrNot** [comment]
Image from console : http://i.imgur.com/Hk6wAUo.png
Image from Network It doesnt have any red items. : http://i.imgur.com/5uU3RlZ.png

**Comment by howardchung** [comment]
yeah I think I found the cause of this and it's incompatbility with the 'color' dependency update we did a few days ago.  (referenced PR should fix the issue)
