### ISSUE TITLE
Going to a new route directly doesn't update tabbar 'active' tab.

### ISSUE THREAD

**Issue by mike-robertson** [odota/ui#59]
To test, go to peers on your profile. Then go to one of your peers pages by clicking the link. This won't update the tabbar's 'active' tab. I'm working on a pr to fix this.

**Comment by howardchung** [comment]
is this fixed @mike-robertson ?

**Comment by mike-robertson** [comment]
There is still an issue with tabs if you are linked to a route. SO if you go to peers, click on one of the links, it won't swap the active tab to overview even though it is showing overview and is on the overview route. This is because of a bug in material-ui tabs which I have put a PR in for but haven't gotten any response yet.

**Comment by howardchung** [comment]
if you try to load an overview with no tab name:
https://ui.yasp.co/players/88367253

The overview tab will not be selected.

**Comment by howardchung** [comment]
@mike-robertson I believe this was fixed with #188 and the new routing code.
