### ISSUE TITLE
7.00 map update

### ISSUE THREAD

**Issue by howardchung** [odota/ui#592]
- [ ] Map update
- [x] How should we display talents?  Currently @blukai 's ability display omits the attribute bonuses.  Should we start displaying everything? #594

**Comment by dartharaknus** [comment]
Do we have a way of detecting 6.x or 7.x matches? Because we want to display old map for old matches.

**Comment by howardchung** [comment]
We can use the start_time to approximate.

**Comment by dartharaknus** [comment]
Isn't there anything they added to the data to use?

**Comment by dartharaknus** [comment]
Like the talent ability stuff.

**Comment by howardchung** [comment]
i guess technically we can try identifying patches like that.  previously I've just maintained an approximate list of patch times and used that though.

https://github.com/odota/dotaconstants/blob/master/json/patch.json

(speaking of which, I need to update that)

**Comment by vamo89** [comment]
![map700](https://cloud.githubusercontent.com/assets/1499336/21369074/68692054-c6ec-11e6-9ee5-19569e54ee2b.png)
is this good enough for put there? Just screen-shooted from the game...

**Comment by blukai** [comment]
http://dota2.gamepedia.com/Minimap#Current
