### ISSUE TITLE
Teamfight hover not showing all gold changes

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#598]
Only a few heroes are being shown.

![opendota dota 2 statistics](https://cloud.githubusercontent.com/assets/5713044/21179710/8f62dae8-c1f5-11e6-887d-3cc9d768afb6.png)

**Comment by mike-robertson** [comment]
Can you provide a link to the example? It'll be a lot easier to debug that way.

**Comment by blukai** [comment]
It shows only players that was killed "Deaths & delta"

**Comment by dartharaknus** [comment]
Why only players who were killed? Gold changes for the players who are alive too.

**Comment by howardchung** [comment]
We have the data for all players, but I think to make the teamfight view less cluttered we opted to only display the players who participated.  @blukai probably just chose to match that behavior for consistency.

**Comment by dartharaknus** [comment]
Well, a player who's alive is not being shown on the timeline. I think we need to make it uniform.

**Comment by dricholm** [comment]
I can do this if it is still needed.

Should it display all heroes and show somehow that a hero has died? ("died" or an icon?)

**Comment by howardchung** [comment]
You can fix with the same PR
