### ISSUE TITLE
Show Talents at the correct levels in Ability builds

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#602]
Currently, there are being shown at lvl 19 and such without any gaps in ability builds.

We need to get the correct number for that.

**Comment by dartharaknus** [comment]
This should also contain the new talent image. And this should be backward compatible with previous dota versions of stats upgrade.

**Comment by howardchung** [comment]
Hmm, there are 4 talent upgrades and 15 ability upgrades.  For the remaining 6 slots, should they just be empty placeholders?

**Comment by dartharaknus** [comment]
Yup, but invoker and meepo are special, I think.

**Comment by howardchung** [comment]
I think the simplest fix is just to remove the "lvl x" label and let it represent build order.
