### ISSUE TITLE
I have played more than 10 matches  using almost all the heroes but my stats,heroes played,expected mmr are showing as null.

### ISSUE THREAD

**Issue by pscrusher101** [odota/ui#605]
- **OS**:
- **Screen Resolution**:
- **Browser/Version**:
- **Link to page with the issue, or screenshot**:

**Comment by howardchung** [comment]
You probably don't have public match data enabled.  Do this in your Dota 2 settings and then click the refresh button on your profile.

**Comment by howardchung** [comment]
let me know if that doesn't fix it/reopen the issue
