### ISSUE TITLE
Manually parsed match that wasn't scored shows up as a loss

### ISSUE THREAD

**Issue by Stereo8** [odota/ui#608]
- **OS**: Windows 10
- **Screen Resolution**: 1920x1080
- **Browser/Version**: Chrome 55.0.2883.87 
- **Link to page with the issue, or screenshot**: https://www.opendota.com/matches/2849823577 

https://www.opendota.com/players/113103177

This match shows up as a loss on my profile, even though it was not scored I manually parsed it. We won the match and the match page says dire victory, as it should, but it shows up as a loss on my profile.

**Comment by howardchung** [comment]
I believe this is a display bug and the counts are still correct, but we should fix it.  Since for not scored matches the radiant_win property is undefined, it'll currently show "Dire Victory" for these matches.
