### ISSUE TITLE
Ward Icons

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#614]
Need minimap icons for observer and sentry wards. Agh's treant ward is also a good idea. Are there anything else like this?

**Comment by howardchung** [comment]
What page is this for?  match vision tab?

**Comment by dartharaknus** [comment]
Yes.

**Comment by dricholm** [comment]
Can I do this?
I am new to React and both contributing but this does not seem difficult.

Just need some icons for them. I found the default minimap icons on the Dota2 wiki, but only in black and white. Should I just repaint them with green/red?

**Comment by howardchung** [comment]
Sure.  I'm currently in the middle of moving a lot of CSS around (including in the vision map, so you might want to wait a couple of days until #1203 is merged to avoid conflicts
