### ISSUE TITLE
Can't pharse my games, it says failed to get match data

### ISSUE THREAD

**Issue by Xalegion** [odota/ui#621]
As title says i can't pharse my matches, but i can download replay from game, whats happening?

**Comment by howardchung** [comment]
Do you have a match ID to debug with?  I'll take a look when I get home from work

**Comment by Xalegion** [comment]
2860816899
2860749267
2860422453

Here you go

**Comment by Xalegion** [comment]
After 2 hours it have started working

**Comment by howardchung** [comment]
Yeah I found the issue and was able to fix it from my phone

**Comment by Xalegion** [comment]
Thx!

**Comment by zyzyii** [comment]
Mine too it has the same problem when I register then I logged in when I logged in my matches didn't generate like there's no matches or no recent matches

**Comment by howardchung** [comment]
did you enable public match history?
