### ISSUE TITLE
my party mmr doesn't match with my dota 2.

### ISSUE THREAD

**Issue by Dreamsha** [odota/ui#622]
Profile : https://www.opendota.com/players/168055204

Opendota Img :
![image](https://cloud.githubusercontent.com/assets/24685958/21369684/ae101b96-c73a-11e6-9f3e-e7af6bd2b92d.png) 

Dota Img :
![image](https://cloud.githubusercontent.com/assets/24685958/21369793/26c05024-c73b-11e6-90e9-0e2755752340.png)

**Comment by howardchung** [comment]
It looks like you haven't played ranked in a while.  It'll attempt to update your MMR after every ranked match you finish.

**Comment by howardchung** [comment]
feel free to reopen/comment if you are still encountering difficulties getting an updated mmr displayed.
