### ISSUE TITLE
Can't pharse a match and OpenDota is not showing my last one

### ISSUE THREAD

**Issue by Xalegion** [odota/ui#632]
As title says

cant pharse : 2868090169

not showing : 2868225805

**Comment by howardchung** [comment]
First issue: Currently some issues with fetching replay salts, I'm investigating.

Second issue: possibly the ingestion/API was behind for a while but it's showing up now.

**Comment by howardchung** [comment]
replay parsing should be functional against.  reopen/comment if that's not the case.
