### ISSUE TITLE
Small localization fixes (for Russian)

### ISSUE THREAD

**Issue by kozhilya** [odota/ui#635]
1. First of all, there was a problem with long tab titles on match page in Russian localization. I'd tried to fix it, and, it looks like I found the way, how to fit them in one string. Still, if you plan to add new tabs, there will be no any possibilities to hold them in this state. 

2. There is a problem with titles for tables separated by teams (like in issue #404). In English sentence like "Dire Unit Kills" is good, but in Russian the sentence should be generate in other order - team name should be after the object (roughly speaking, "Unit Kills by Dire"). For now, in Russian localization for fixing this I used dash ("Dire - Unit Kills"), But on player page in "Records" tab "Last Hits" string is also have this dash as it was inserted in `heading_last_hits` string (because of those table titles). I don't know, where the problem, because searching by string name give only in match page. Records page get this value somewhere outside the project. It's looks strange and needs to be fixed.

3. Also, in Localization select list Russian should be not "ру́сский" but "Русский" - with uppercase first letter and without accent mark (obviously it was copied from Wikipedia).

4. Can you add for left section in Timeline (with team names and -1:30) CSS-rule `min-width: 70px;` somehow? It shouldn't affect the entire timeline, but if it will be set, then in Russian team names will not break on 2 lines. It's not vital, but a little better.

At the end, please, update the Russian localization from crowdin.

**Comment by howardchung** [comment]
1) We haven't added any new tabs in a while, but I'll keep it in mind.  Probably just need to shrink teh font size.

2) Records page shares the same string, here's the code:
`  displayFn: (row, col, field) => strings[`heading_${field}`],`
I think we can just make the match page show `${team} - ${title}` for all languages, to avoid word order issues.

3) Should be a quick fix.  String is here: https://github.com/odota/ui/blob/5fe46ae824890cb4b82854fafbb3b2a2530fa693/src/lang/index.js#L52

4) @blukai will that be ok for all languages?

**Comment by howardchung** [comment]
Looks like @albertcui fixed number 3 this morning.

I fixed the second issue.
