### ISSUE TITLE
Buybacks

### ISSUE THREAD

**Issue by Tommassino** [odota/ui#645]
Hello,
as far as i know, its impossible, or pretty hard, to view how many times a hero bought back. You can see the gold a hero spent on buybacks in the Farm tab under gold sources, but not how many times a hero bought back. For some reason buyback events are not included in the Log either. How hard would it be to add this info, at least to the Farm tab (it might not really belong there?), or to the log?

**Comment by howardchung** [comment]
I think the data is already extracted, it's just a matter of putting it on the page.  IIRC each player has a buyback_log so we just need to put it on the performance tab or something.
