### ISSUE TITLE
"Pro Players Played With" order by Matches doesn't work

### ISSUE THREAD

**Issue by fireattack** [odota/ui#647]
Example: https://www.opendota.com/players/55649904/pros

It doesn't work in two ways:

1. If you never sort by other column, click on "match" does nothing.
1. If you sorted by other column(s) first, then click match, the sorting arrow UI element appears but still does nothing.

**Comment by howardchung** [comment]
Looks like we just have to supply something for the `field` prop in the columnDef, even if we are overwriting the sortFn.

**Comment by bschilli2** [comment]
I also have an issue I played a match with miracle and it doesn't come up I have proof that it's him on dota. Match 2478148476

**Comment by howardchung** [comment]
Probably their expose public match data setting is off, which causes them to appear as anonymous
