### ISSUE TITLE
Enhance display of 'killed' in Teamfights page

### ISSUE THREAD

**Issue by TrentBartlem** [odota/ui#648]
On the teamfights page (e.g. https://www.opendota.com/matches/2886620915/teamfights)

It's quite difficult at a glance to tell who lived and who died. Would it be possible to make deaths > 0 stand out in some way? red+bold letters, or tinting the row?

**Comment by howardchung** [comment]
Sure, I think that shouldn't be too hard.  @covertPZ @mike-robertson @blukai ?

**Comment by mike-robertson** [comment]
I think it's a great idea. Thanks @TrentBartlem. I agree, it should be fairly simple

**Comment by covertPZ** [comment]
I think red+bold would be the better option here to keep the tables consistent throughout the app. I was fiddling and will push something shortly.
If we want to tint the row I can revisit my change.

**Comment by covertPZ** [comment]
Actually, thinking about this a bit more. We could use the in-game death icon in this column and just have a multiplier for cases of diebacks. Thoughts?

**Comment by TrentBartlem** [comment]
Will that work with the sortable column?

**Comment by howardchung** [comment]
Yes, we can define separate functions for display and sort

**Comment by covertPZ** [comment]
Issue i'm having right now... Finding that death icon. Anything I search for just gives me pictures of death prophet :(

**Comment by howardchung** [comment]
I think we used to use the unicode character skull in old UI--but it may work better to use an image if you can find one:

http://www.fileformat.info/info/unicode/char/1f480/index.htm
