### ISSUE TITLE
My match statistics do not take into account in ranking

### ISSUE THREAD

**Issue by Alexalex14228** [odota/ui#649]
14 days ago i played as Juggernaut and got the highest gpm/xpm, dmg/sec, etc, but these statistics do not take into account in my rankings
My ranking - https://www.opendota.com/players/158519110/rankings?hero_id=8
Match - https://www.opendota.com/matches/2880758066
Same problems with some other matches

-- Windows 10
-- Opera browser/newest version

**Comment by howardchung** [comment]
Stats do not affect ranking, only wins and average MMR in the match do.

You can read more about it here: http://blog.opendota.com/2016/09/30/explaining-rankings/
