### ISSUE TITLE
Games not opening on OpenDota

### ISSUE THREAD

**Issue by juvi97** [odota/ui#652]
Some of my recent games refuse to open in OpenDota. They do not open for other people either (my friends are unable to open them) and the device I use does not matter. However, the same matches do open in Dotabuff.

The nonfunctional pages:

https://www.opendota.com/matches/2911914137
https://www.opendota.com/matches/2909997131

Please let me know if the issue is on my end. Thanks!

**Comment by howardchung** [comment]
Looks like the data for roshan kills changed (no more player slot data?) and this is causing the overview timeline is crash.  Putting in a fix now
