### ISSUE TITLE
yugoslavia flag broken

### ISSUE THREAD

**Issue by howardchung** [odota/ui#658]
Possibly because Yugoslavia isn't a country anymore.  Did we use a hotlinked image for this @blukai since i don't think it's in the country data?

https://www.opendota.com/distributions/country_mmr

**Comment by blukai** [comment]
Yes, Yugoslavia and a some other are no longer a countries, but for some reason people still specify its.
I thought that flags from wikipedia cannot be removed/changed. I'll open pr to fix it.
