### ISSUE TITLE
Bad links on top donater page

### ISSUE THREAD

**Issue by sqw23** [odota/ui#670]
Top donaters (https://carry.opendota.com/) are linked to the wrong page. Their names link to "https://**carry**.opendota.com/players/111111" instead of "https://opendota.com/players/11111"

**Comment by howardchung** [comment]
This is https://github.com/odota/carry/issues/3

@albertcui please fix this, it's been open 3 months and it'll take 5 minutes.

**Comment by albertcui** [comment]
Fixed odota/carry#3
