### ISSUE TITLE
code typo: `primary1Color` instead of `primaryColor`?

### ISSUE THREAD

**Issue by noformnocontent** [odota/ui#691]
https://github.com/odota/ui/blob/master/src/components/App/App.jsx#L27

**Comment by howardchung** [comment]
@blukai ?

**Comment by blukai** [comment]
Nope, everything is fine. 🦄 
http://www.material-ui.com/#/customization/themes

**Comment by noformnocontent** [comment]
oh, i assumed since its the only property which has `1` at seemingly random place and no `2` or such..

nevermind then :D

closing.
