### ISSUE TITLE
Cosmetics name and rarity are displayed wrong

### ISSUE THREAD

**Issue by dralois** [odota/ui#701]
As you can see in the attached picture the name and the rarity of items are combined, should be a simple fix (maybe add brackets around the rarity).

![test](https://cloud.githubusercontent.com/assets/4374949/22793388/ff080e8c-eeef-11e6-850d-911884d63551.png)

**Comment by blukai** [comment]
Looks like something went wrong with inflictorWithValue in https://github.com/odota/ui/tree/master/src/components/Visualizations
I guess we should merge this issue with #700

**Comment by howardchung** [comment]
I don't think cosmetics use inflictorWithValue.  I think this is a break in ReactTooltip

**Comment by howardchung** [comment]
Yeah I confirmed issue (and #700 ) go away with 3.2.3.

Here's the changelog, I don't see anything breaking but I'll lock the version anyway.
