### ISSUE TITLE
Don't show event matches by default

### ISSUE THREAD

**Issue by dartharaknus** [odota/ui#704]
Let's add an option in the settings whether to show event matches or now. Let's switch it off by default for everyone.

**Comment by howardchung** [comment]
This is the aggregation behavior already, but I thought it was better to list the insignificant matches in /matches so users don't wonder where their no stats recorded/ARDM/AD matches are.

**Comment by dartharaknus** [comment]
Can't we identify the Dark Moon matches? When I mean event matches, I mean these kind of ones. I wouldn't consider ARDM/AD events.

**Comment by howardchung** [comment]
They have game mode 19, but idk if valve is planning to reuse that ID for something in the future that we want to include.

**Comment by dartharaknus** [comment]
Has valve ever reused game mode ids? I don't think so. It's a pretty bad thing to do.

**Comment by TrentBartlem** [comment]
Perhaps do what Dotabuff does, and de-emphasise them?

<img width="647" alt="screen shot 2017-02-14 at 2 12 25 pm" src="https://cloud.githubusercontent.com/assets/171650/22914968/b22fbb90-f2bf-11e6-948a-4e68b2592dc2.png">

**Comment by howardchung** [comment]
Think this is a temporary issue since event matches don't always happen and they don't always spam the match history.  We can reopen/revisit if it becomes a problem again.
