### ISSUE TITLE
Pro Players Played With: Not Showing

### ISSUE THREAD

**Issue by bschilli2** [odota/ui#710]
Okay so a while ago I had the honoring of playing a match with miracle in my party I didn't realize it was actually him till party way through the game I can find the match on here but it doesn't recognize miracle here is the match ID and you could also look at the chat logs on dota I can get on that game and see his profile with 9k mmr it's him and I'd like it to show I've played with him match ID  Match 2478148476

**Comment by bschilli2** [comment]
Sorry about the Mumbo jumbo

**Comment by howardchung** [comment]
If the player does not have public match data enabled they show up as anonymous.  If at some point they do enable it, you can request a refresh on their profile and it should update.
