### ISSUE TITLE
add filter links to with/against columns on /players/:id/heroes

### ISSUE THREAD

**Issue by howardchung** [odota/ui#720]
Should be easy, just do the same as the played as column:

https://www.opendota.com/players/71313111/heroes

**Comment by BrunoWilkinson** [comment]
Hey I'am up for the challenge :)

**Comment by howardchung** [comment]
go for it!  this should be pretty straightforward, but feel free to ask for help on Discord if needed.

**Comment by masad-frost** [comment]
@BrunoWilkinson basically make the with a link to "...?with_hero_id=$heroid" and same with against.

**Comment by BrunoWilkinson** [comment]
@masad-frost thx I got confused with the filter log and I didn't see the link MP, I will try to finish this in the end of the week, I wish I could do it before but I'am super busy next few days
