### ISSUE TITLE
Death counter differs

### ISSUE THREAD

**Issue by justmeeee** [odota/ui#729]
Overview says Warlocks kda is 17/7/26: https://www.opendota.com/matches/3012736180/overview
Combat says he killed 20 dire heroes: https://www.opendota.com/matches/3012736180/combat

**Comment by howardchung** [comment]
So this is a due to a really long-standing issue where the combat log counts aegis/reincarnation deaths.
https://github.com/odota/core/issues/726

Unfortunately there is still no fix for this.
