### ISSUE TITLE
Cannot exclude or include players in filtering anymore

### ISSUE THREAD

**Issue by neky92** [odota/ui#742]
When you try to filter your games, when you type ID in included or excluded account ID, it does nothing, even pressing enter does nothing, it used to work, but now it doesn't, only way to get it to work is to change the link by adding &excluded_account_id=

**Comment by howardchung** [comment]
@masad-frost seems like this change broke all filters:
https://github.com/odota/ui/commit/76c89d60544ed95dd005b6bb92516d1854702abd

I'll undo the change to FormGroup
