### ISSUE TITLE
Add links to pages on player overview

### ISSUE THREAD

**Issue by masad-frost** [odota/ui#751]
Recent matchs -> matches | Players -> peers | Heroes -> heroes. Might be an overkill since we have the links at the top.

![image](https://cloud.githubusercontent.com/assets/1994028/23339956/dd8ca14c-fbe1-11e6-95ce-843ff0b50926.png)

**Comment by howardchung** [comment]
I personally find it fine to just use the top navbar, but if people think this is better, we can do this too.  Maybe get some input from Discord?

**Comment by howardchung** [comment]
Guessing this is a no?  Feel free to submit the pull request anyway so we have a record of the code if we decide we want this later.
