### ISSUE TITLE
Roaming heroes

### ISSUE THREAD

**Issue by masad-frost** [odota/ui#759]
Use match/player/is_roaming implemented in odota/core#1414

Obviously should be used in the match performance tab, maybe add a tooltip on the `Roaming` field that displays the lane they were mostly on (match/player/lane_role).

Not sure where or how else can we use this.

**Comment by howardchung** [comment]
This should be pretty easy

**Comment by maschwenk** [comment]
Something I'd be interested in picking up. This project is awesome.

**Comment by howardchung** [comment]
Sure!  Clone the UI and get it running.  The API response already contains this data, so this should just be as simple as adding `(Roaming)` to the column in the performances tab if the `is_roaming` property is true.
