### ISSUE TITLE
Matches page: Match id should be the first column

### ISSUE THREAD

**Issue by brunovinicius** [odota/ui#770]
I (re)started using the site recently and I find the column ordering very misleading because I expected that clicking the hero name would navigate to the match details page, but its actually the match id that does it. I figured out that the column position is whats making it confusing to me. As this is the matches list, I think is kind of default behavior to have the link that carries you to the matches page first. I`m no UX expert, but  this is my gut feeling about it. What you guys think? 

PS: site is much better than the first version I visted a while ago, and I saw some code and its actually great. Great job guys! Keep it up!

**Comment by howardchung** [comment]
Sure, we can swap the match ID to the left.  @blukai any opinions?

**Comment by blukai** [comment]
I think that swapping columns may confuse a lot of users that accustomed to current order.
Probably to get out from this situation and not do worse, we can make clickable entire row.

**Comment by masad-frost** [comment]
Making the whole row a link might mitigate this. Highlighting the row and te matchId on hover.

**Comment by brunovinicius** [comment]
By all means guys, if you mind hearing an advice, either a UX change is
beneficial in most aspects or is not a good change. If you believe changing
columns position might confuse user than this solution is probably sub
optimal. That being said, I believe the muscle memory for going on first or
last column to dig in item details is so strong a pattern that it would
make the transition close to effortless even for current users. Again, I
wish I could point studies and stuff to back up my opinions, but I can't.
AB testing or even watching people use the site to measure for missclicks
would help too, but objectively speaking it's a so minor so effortless
change that is easier to see it in action and get feedback right away...
Hope this helps 😅

PSA: I find myself too much invested in this narrative now and my opinions
might be extremely skewed

**Comment by howardchung** [comment]
Plan is to just make the hero name link go to the match, see #1167
