### ISSUE TITLE
I can not see my last games as solving

### ISSUE THREAD

**Issue by nNnFEARbr** [odota/ui#790]
When I enter the OPENDOTA does not show my last matches even with the public profile can someone help me

**Comment by howardchung** [comment]
Do you have a profile link?

**Comment by nNnFEARbr** [comment]
link da steam??

**Comment by howardchung** [comment]
Or OpenDota profile

**Comment by nNnFEARbr** [comment]
What happens, is logged with my STEAM account is unknown and so it is not possible to see my games and my profile and audience as well. Do you know how to help me?

**Comment by howardchung** [comment]
If you can provide your account ID then I can check to see if you have public match data exposed.

**Comment by nNnFEARbr** [comment]
This is 76561198124043063

**Comment by howardchung** [comment]
It appears that you don't have Expose Public Match Data enabled (this is a setting in the client).

```
{
"result": {
"status": 15,
"statusDetail": "Cannot get match history for a user that hasn't allowed it"
}
}
```

Try enabling it and then clicking the "refresh" button on your OpenDota page.

**Comment by nNnFEARbr** [comment]
how do I do that?

**Comment by howardchung** [comment]
It's one of the settings in your game client.  Try looking through the options

**Comment by blukai** [comment]
@nNnFEARbr 
![image](https://cloud.githubusercontent.com/assets/20866892/23945582/b1296f44-097f-11e7-8e91-767ce72a9b5e.png)

**Comment by nNnFEARbr** [comment]
Thank you, man, that might work.
