### ISSUE TITLE
Matches not automatically parsing

### ISSUE THREAD

**Issue by davejkish** [odota/ui#801]
Hi,

My matches have not been automatically parsing, even though it says they will be parsed.
![image](https://cloud.githubusercontent.com/assets/19862283/23868221/fd99e458-07f4-11e7-984f-16249f32a938.png)

I can manually parse the matches.
Profile:  29492429

Thanks!

**Comment by howardchung** [comment]
It looks like you are playing almost all Ability Draft matches.

I disabled automatic replay parsing for non-significant game modes (AD/ARDM, etc.) during Dark Moon to avoid the additional load.
