### ISSUE TITLE
Misaligned first column side lines on tables

### ISSUE THREAD

**Issue by ivanpepelko** [odota/ui#802]
- OS: Arch Linux
- Screen Resolution: 2K, FHD
- Browser/Version: Mozilla Firefox 52.0

The coloured bar and 'party lines' on first table column are misaligned on following table views:
- overview
- matches
- match/overview
- match/benchmark
- match/combat
- match/farm
- match/objectives
- match/actions
- match/analysis
- match/log
- match/chat

Screenshots:

![image](https://cloud.githubusercontent.com/assets/7328461/23894455/776fe838-08a2-11e7-8979-e643e381609a.png)

![image](https://cloud.githubusercontent.com/assets/7328461/23894474/890b8c78-08a2-11e7-84fb-d94172e97c8c.png)

**Comment by howardchung** [comment]
Might be some CSS that firefox handles differently from Chrome.  @blukai do you know what might cause this?

**Comment by blukai** [comment]
Maybe something wrong with flexbox, can't reproduce it's on win 10 with ff 52

**Comment by howardchung** [comment]
@masad-frost is this something we can verify with browserstack?  and maybe test fixes

**Comment by masad-frost** [comment]
No Linux support on browserstack.

I ran my arch partition, can't reproduce on FF 52, same resolution. Weird,.

**Comment by masad-frost** [comment]
Ok, now I can reproduce on Ubuntu FF52, wtf. I think flexbox is broken. I can manually reproduce this on chrome by removing `display: flex`. I think `align-items: center` should fix it. I'll send a PR soon
