### ISSUE TITLE
Story should note which tower dies

### ISSUE THREAD

**Issue by TrentBartlem** [odota/ui#816]
The story below is nice, but it lacks context. Being able to tell _which_ towers are being pushed would be really helpful to determine who is pushing which lanes

<img width="462" alt="screen shot 2017-03-20 at 6 10 38 pm" src="https://cloud.githubusercontent.com/assets/171650/24092218/9aa38670-0d98-11e7-9391-6f141ff5ad62.png">

**Comment by howardchung** [comment]
@mdiller is this possible?  I know the specific tower isn't available in the objectives log, but maybe tower kills could be added to kills_log for each player (this would not include towers killed by lane creeps though)

**Comment by mdiller** [comment]
Yeah if it was added to kills_log it'd be possible, but since it's common for towers to be killed by lane creeps, it would be more useful if we could figure out which towers those are as well.

**Comment by howardchung** [comment]
We think there's a way to get this data, see https://github.com/odota/core/issues/1486 for details

**Comment by howardchung** [comment]
fixed in #1066
