### ISSUE TITLE
Look like the 'Benchmark' is not working properly

### ISSUE THREAD

**Issue by Crazy3lf** [odota/ui#829]
It is all showing 0.00%.
Screenshot from [this match](https://www.opendota.com/matches/3071534823/benchmarks)
![image](https://cloud.githubusercontent.com/assets/6470547/24225972/950b0f1e-0f9e-11e7-98af-fa427d35ae0f.png)

**Comment by howardchung** [comment]
This can happen if the steam API is down for a while.  The old benchmark data expires and there's no new data coming in so it shows 0.  It should automatically recover when the steam API is back up.
