### ISSUE TITLE
Failure to load story tab on ticketed match, resulting in all tabs failing to load

### ISSUE THREAD

**Issue by Terpcasl** [odota/ui#833]
- **OS**: Windows
- **Screen Resolution**: 1920/1080
- **Browser/Version**: Chrome
- **Link to page with the issue, or screenshot**: https://www.opendota.com/matches/3067978105
When switching from the overview tab to any other tab, there is no problem. When trying to switch to the story tab, there is no change in the page data. Any subsequent change in tabs results in no change to page data either. When trying to load the story page directly, nothing is displayed.

**Comment by howardchung** [comment]
This is the same issue as #830 , and the fix has already been committed.

I'll push it to production now
