### ISSUE TITLE
Match story contains "Unrecognized Hero"

### ISSUE THREAD

**Issue by MistahCheese** [odota/ui#837]
https://www.opendota.com/matches/3071310248/story

As you can see, on the first line, the match story says "First blood was drawn when Keeper of the Light killed Unrecognized Hero at 1:23." I'm fairly sure it was Slardar that died. That's the only place where the hero isn't recognized in the story, though, everywhere else it displays all the names of every hero correctly. I haven't tried to re-parse because I figured it would be a good idea to let devs know about this bug and I didn't want the example to disappear.

**Comment by howardchung** [comment]
@mdiller possibly a problem with reading the first kill?  The log data looks fine.

**Comment by coreymaher** [comment]
It looks like the first blood event comes at a different time than the kill event.
If you look at the log the first blood event is at 1:23 while the kill is at 1:24.

**Comment by howardchung** [comment]
Instead of this line:
`player.kills_log.filter(kill => kill.time === match.objectives[fbIndex].time),`

Maybe we should just find the first kill event

**Comment by mdiller** [comment]
Ok sounds good. Should I also change the way timeline finds it? I think I took how first blood was calculated from there, so it probably has a similar problem.

**Comment by howardchung** [comment]
sure, that sounds good
