### ISSUE TITLE
Player's Avatar Not Showing

### ISSUE THREAD

**Issue by gqy117** [odota/ui#838]
OS: Windows 10
Screen Resolution: 4k
Browser/Version: Chrome/Latest

Here is the player page:
https://www.opendota.com/players/138264280/overview

Here is the steam profile page:
http://steamcommunity.com/profiles/76561198098530008/

Cheers

**Comment by howardchung** [comment]
If this is you, logging out and back in again should refresh the profile image.  Otherwise, it updates periodically from the players who have finished matches recently.
