### ISSUE TITLE
"Unable to parse replay" but the replay was successfully parsed

### ISSUE THREAD

**Issue by kryogenic** [odota/ui#840]
I believe what happened here is the job progress reporting timed out cause the parsing took longer than usual. The game in question was 90 minutes long. Here's the link https://www.opendota.com/matches/3075703244/

**Comment by howardchung** [comment]
This is probably a transient error.  The UI is actually making polling requests to check the state of the job, but I think if any of those encounters an error it will display the error message without affecting the actual processing of the job.
