### ISSUE TITLE
/heroes shouldn't be paginated

### ISSUE THREAD

**Issue by space-funerals** [odota/ui#841]
If I want to find a hero's pick rate/win rate, I have to ctrl-f through 6 pages. It seems more user friendly to just have all of the data on one page.

**Comment by howardchung** [comment]
The original version did this, but the tradeoff is that the header rows disappear if you scroll down too much.  If this is more acceptable than having to page, I can put it back

**Comment by blukai** [comment]
Probably we can add a filter input
