### ISSUE TITLE
Bug of player trending line.

### ISSUE THREAD

**Issue by kxxoling** [odota/ui#848]
The trending line of me looks strange, there shouldn't have 2 matches per time, it must be a bug of the tied line.

![image](https://cloud.githubusercontent.com/assets/1227139/24390991/e9f90bb0-13be-11e7-8a26-aab17b29b1cb.png)

- **OS**: macOS
- **Browser/Version**: Chrome 57
- **Link to page with the issue, or screenshot**: https://www.opendota.com/players/121230511/trends/loss

**Comment by howardchung** [comment]
the c3 spline graph implementation seems to be a bit buggy.  Switched to line graph (straight lines)
