### ISSUE TITLE
"showBar" column property for tables

### ISSUE THREAD

**Issue by howardchung** [odota/ui#86]
currently implemented for percent columns.  Allow setting a property on any column to display bars relative to the maximum value of that column in the given table.

**Comment by howardchung** [comment]
I think we have all the pieces for this already.  We just need to add the `TablePercent` element to Table, and render it if the columnDef specifies `true` for `showBar`.  The table can then find the max (similar logic to how the sum works right now), and then pass the value/max to TablePercent.

**Comment by masad-frost** [comment]
> Allow setting a property on any column to display bars **relative to the maximum value** of that column in the given table.

Relative to max or relative to total like we do with the percent coliumns. I think the latter is more appropriate.

**Comment by howardchung** [comment]
Total is not well defined for non-percent columns.  We should support both.
