### ISSUE TITLE
Adding date as feature on table

### ISSUE THREAD

**Issue by neverperfect** [odota/ui#863]
For a project I'm currently working which is about prediction of upcoming leagues I need data of the dates of each matches, is there a way to show "dates" column on the table?
Or if it's not currently implemented, is it possible to realize this.
Thanks in advance. =)

**Comment by howardchung** [comment]
Is this for the explorer?  I can add it as a column in the preconstructed  query.

**Comment by neverperfect** [comment]
Yes, I meant for the explorer. Please do add it when you can.
Thank you so much :)

**Comment by howardchung** [comment]
Do you need the start_time for each match, or are you interested in the min/max start_time for a league?

**Comment by neverperfect** [comment]
Basically the day of each matches, when they were played.

**Comment by howardchung** [comment]
http://hchung.westus.cloudapp.azure.com:8080/explorer?

does this look ok?  or would you prefer all numbers, instead of using text for the month

**Comment by howardchung** [comment]
fixed in #809
