### ISSUE TITLE
"Teams" column displaying current player's team, not the match's team

### ISSUE THREAD

**Issue by neverperfect** [odota/ui#865]
adding "teams"/"teams.name" syntax as one of the column on the script would bring out the current player's team not the team which the player played as during that match. 
For example if I would call out KuroKy's past match data, he would still be counted as playing as Team Liquid on The International 2014, even though he played as Na'vi during the time.

**Comment by howardchung** [comment]
Right now we use the current team-player link, since I think it's more likely that users are interested in checking data for the current team (e.g. running a query filtered with Alliance returns data for matches that the current roster has played).

 What's the use case for using the "team at the time of the match"?

**Comment by neverperfect** [comment]
So if I wanted to call the time Pajkatt was playing as Alliance is it possible?
When I tried searching for player: Pajkatt, and team: Alliance, it returned zero results.

**Comment by howardchung** [comment]
I think there'll need to be two distinct fields, one for "current team" and one for "team at time of match"

**Comment by neverperfect** [comment]
I see.. As for now is there a query on the SQL to call current team?
Or it hasn't been implemented yet?

**Comment by howardchung** [comment]
Sure, you can join match with team_match then filter by team_id

**Comment by neverperfect** [comment]
Sorry, how can I do this? I don't find team_match as one of the query on the drop down query..
Do you mind if you can explain me in detail or step-by-step of it? XD

**Comment by howardchung** [comment]
> Sorry, how can I do this? I don't find team_match as one of the query on the drop down query..
Do you mind if you can explain me in detail or step-by-step of it? XD

Here's an example.  Na`Vi's team_id is 36, so the following query returns the match_ids of the 1236 matches they've played in:
https://www.opendota.com/explorer?sql=select%20match_id%20from%20matches%0Ajoin%20team_match%20using(match_id)%0Awhere%20team_id%20%3D%2036%0Aorder%20by%20match_id%20desc

**Comment by neverperfect** [comment]
This gives me an error for some reason..
![skripsi1](https://cloud.githubusercontent.com/assets/10155244/24751952/cfce8b28-1af5-11e7-8470-21df3e1d5cc0.png)
![skripsi2](https://cloud.githubusercontent.com/assets/10155244/24751963/e3304698-1af5-11e7-964c-b9ad282dcf70.png)

**Comment by howardchung** [comment]
Since you're selecting teams.name you also need `JOIN teams using(team_id)`

**Comment by neverperfect** [comment]
I used both JOIN teams using (team_id) and JOIN team_match using (match_id) on the second SQL (second screenshot) and got errors still.. xD

Also if I use more than 1 team_id, and display the team names?
What I'm trying to accomplish is call player's team history (with the team name as one of the column)

**Comment by howardchung** [comment]
This should work (EternalEnvy's match history):

https://www.opendota.com/explorer?sql=select%20matches.match_id%2C%20teams.name%0Afrom%20matches%0Ajoin%20player_matches%20using(match_id)%0Ajoin%20team_match%20using(match_id)%0Ajoin%20teams%20using(team_id)%0AWHERE%20player_matches.account_id%20%3D%2043276219%0Aorder%20by%20match_id

Not sure what you mean by more than one team_id.  Each match-player combination can only have one team associated with it, so it's one team name per row.

**Comment by neverperfect** [comment]
Oh thank you so much, that's what I need :D

**Comment by howardchung** [comment]
```
select 
matches.start_time,
kills,deaths,assists,
xp_per_min,gold_per_min,
matches.match_id, 
teams.name,
player_matches.account_id,
leagues.name leaguename
from matches
join match_patch using (match_id)
join leagues using (leagueid)
join player_matches using(match_id)
join team_match using(match_id)
join teams using(team_id)
WHERE player_matches.account_id = 43276219
AND team_match.radiant = (player_matches.player_slot < 128)
order by match_id
```

Couple of issues with your query:
* The last column name in the SELECT should not have a comma
* Removed notable_players since you don't need it, and it was creating a second column called team_id.  using() is shorthand for `ON teams.team_id = team_match.team_id` so when there are multiple columns called team_id postgres gets confused
* Removed the "left" from your query.

It's LEFT JOIN, not JOIN LEFT.  what it does is that it means that it will keep rows from the left side (above the LEFT JOIN) even if it can't find a matching row on the right now (the table you're joining to).

https://www.w3schools.com/sql/sql_join_left.asp

**Comment by neverperfect** [comment]
Thanks so much, you saved me from weeks of data mining XD
All the best for OpenDota's Data Explorer Project!

**Comment by howardchung** [comment]
You can leave the issue open, I should add field selectors for both current and historic teams.

**Comment by howardchung** [comment]
I've added a new field called "organization" that does not change regardless of roster shuffles.

**Comment by howardchung** [comment]
@neverperfect e.g. the following gets the matches that pajkatt played on alliance:
http://hchung.westus.cloudapp.azure.com:8080/explorer?organization=111474&player=87285329&group=&team=
