### ISSUE TITLE
OpenDota API not concistent with documentation for GET /players/{account_id}/matches 

### ISSUE THREAD

**Issue by BjornArnelid** [odota/ui#880]
The expected array "heroes" is missing from the result.

**Comment by howardchung** [comment]
You can request it by passing the `&project=heroes` in the URL.  It's not one of the default fields though so maybe we should remove it.  You can request any field that's in the schema, the defaults only return a core subset of about 10 fields for efficiency.

**Comment by BjornArnelid** [comment]
hmm, i get {"error":"Not Found"} if i add that to my query?

**Comment by howardchung** [comment]
What's the full URL you're trying?

**Comment by BjornArnelid** [comment]
https://api.opendota.com/api/players/75579712/matches&project=player

**Comment by BjornArnelid** [comment]
https://api.opendota.com/api/players/75579712/matches?project=heroes works.

**Comment by howardchung** [comment]
Use ? instead of &.  Ampersand if you need to add any additional query params.

**Comment by BjornArnelid** [comment]
I figured it out eventually. 
But to get back to the actual bug, i really do think that the response sample should sync with the example query in your documentation.

**Comment by howardchung** [comment]
I added a note that this field requires `?project=heroes`:
https://github.com/odota/core/commit/43fb9c9797028182034a5acedbfd787d86c5ceb8
