### ISSUE TITLE
Unable to see MMR Graph

### ISSUE THREAD

**Issue by Cliff-Chua** [odota/ui#881]
Hi,

I am unable to see my MMR graph as attached from the image. I am using google chrome and windows 10 64-bit.

![image](https://cloud.githubusercontent.com/assets/27294184/24918111/c2a2f73e-1f11-11e7-9d90-45e42cec97b1.png)

**Comment by coreymaher** [comment]
@Cliff-Chua You have to add your Solo and/or Party MMR to your in game profile and then play ranked games for it to show up here.

**Comment by howardchung** [comment]
@coreymaher is correct, please reopen/comment if you have any additional issues getting the MMR data to show up.

**Comment by Cliff-Chua** [comment]
Thank you all so much for the info!
