### ISSUE TITLE
there is no data about me at all

### ISSUE THREAD

**Issue by Totyano** [odota/ui#896]
hi
![image](https://cloud.githubusercontent.com/assets/27620441/25070631/3760cda6-22ac-11e7-9aa9-2a9c3410f1a0.png)

i have an issue, when i login to my page in this ste i see no data or statistics at all, its all zeroes or "null"> please fix my problem ty.

**Comment by Luchanso** [comment]
I think it's because your profile is private.

**Comment by howardchung** [comment]
Yeah, enable "Expose Public Match Data" in the client and then click the "refresh" button to have it fetch your previous matches.
