### ISSUE TITLE
verified

### ISSUE THREAD

**Issue by noonefriends** [odota/ui#903]
can i get a verified , played in alot of good team x vs like spirit empire etc players/187758589 acc ty

**Comment by Luchanso** [comment]
Hi, @noonefriends 

Verified status takes from the steam API: https://lab.xpaw.me/steam_api_documentation.html#IDOTA2Fantasy_570_GetProPlayerList_v1

**Comment by Luchanso** [comment]
Duplicate #828

**Comment by howardchung** [comment]
It's possible to start maintaining our own list in addition to what the API gives us, but we need to set up some way to validate that a requester does indeed own a particular Steam account.
