### ISSUE TITLE
MMR AND DOTA 2 RECENT GAMES NOT R

### ISSUE THREAD

**Issue by eugeneong1** [odota/ui#908]
![untitled](https://cloud.githubusercontent.com/assets/27804277/25219402/f81e4604-25e0-11e7-915d-04fce362e606.png)

**Comment by howardchung** [comment]
Did you disable the Expose Public Match Data setting?

**Comment by eugeneong1** [comment]
Ow sorry for that. It's my fault i disabled it the last time. lol thanks mate
