### ISSUE TITLE
Heroes on buildings map

### ISSUE THREAD

**Issue by blukai** [odota/ui#910]
Display hero positions (lanes) on buildings map, also probably if it's possible - heat-map from the performances page on icon hover.

**Comment by howardchung** [comment]
I think we have the data for both of these already, so it's definitely possible!

**Comment by samwhite** [comment]
I've started working on this one - will hopefully keep you posted / open a PR soon!

<img width="312" alt="screen shot 2017-05-13 at 17 09 32" src="https://cloud.githubusercontent.com/assets/5761771/26027069/fcb126ac-37fe-11e7-8cf3-71a694f4299c.png">

**Comment by howardchung** [comment]
Awesome, thanks!

**Comment by howardchung** [comment]
@samwhite any update on this?

**Comment by dricholm** [comment]
It seems that this has been inactive for a while so I started implementing it.
I can submit a PR for hero icons soon.

Currently I have it like this: Display the player icon on the corresponding lane and have a React Tooltip for it where I can say whether the player is roaming or not. Is this way okay?
Also was wondering about the size and positions of the icons.
Any other recommendations or tooltip information suggestions?

![image](https://user-images.githubusercontent.com/32329112/31484622-f8721274-af6b-11e7-93f2-fff5c9a794cf.png)

**Comment by howardchung** [comment]
LGTM.  Is it possible for the icons to cover the buildings if say, everyone goes mid?

**Comment by dricholm** [comment]
I modified it somewhat from before: made the icons smaller and adjusted positions a bit.
No buildings or other heroes can get covered.

For example even if I add everyone to every lane on their own team (this looks a bit confusing but can never happen, it would mean 20v20):
![image](https://user-images.githubusercontent.com/32329112/31524466-d6566558-aff4-11e7-9d74-102e5bd53e63.png)

Normally it looks like this:
![image](https://user-images.githubusercontent.com/32329112/31524527-27058812-aff5-11e7-9faa-f95bd5a848cd.png)
