### ISSUE TITLE
New story line: Who predicted they would win the game?

### ISSUE THREAD

**Issue by evaryont** [odota/ui#911]
@howardchung mentioned in the discord chat that the replays do include "player has predicted!" data. It'd be neat to see that added to the story view as well.

Not sure if it's parsed and available in the JSON yet.

Would be super cool if streak data was available too. But that's not important. Not sure how universal it is, since charms don't really have a "streak" per se.

Would also be amusing to mention at the end of the story to mention how the predictions panned out.

**Comment by howardchung** [comment]
@mdiller

**Comment by dartharaknus** [comment]
👍
