### ISSUE TITLE
My stats arent being listed

### ISSUE THREAD

**Issue by cybercrypt** [odota/ui#913]
![screenshot 36](https://cloud.githubusercontent.com/assets/25293582/25304483/c6e54faa-2785-11e7-8d49-4d893a9c2d52.png)
I have over 700 games played.

**Comment by Luchanso** [comment]
Maybe your profile is private?

**Comment by cybercrypt** [comment]
![screenshot 37](https://cloud.githubusercontent.com/assets/25293582/25304559/2751aaea-2787-11e7-93b2-82e3b652401f.png)
It's set to public

**Comment by Luchanso** [comment]
This setting toggle in Dota 2

**Comment by cybercrypt** [comment]
That was it. Thank you :)
