### ISSUE TITLE
Adjust XP totals for graph section to the new experience values.

### ISSUE THREAD

**Issue by sneakyimp1** [odota/ui#924]
Current behavior: Some matches show hero's never reaching level 25 in the graphs even though they have in the game. Most likely due to the recent changes to XP needed to reach a level.

https://www.opendota.com/matches/3143720104/graphs

Current experience vales to adjust to.

**Comment by howardchung** [comment]
File to update:
https://github.com/odota/dotaconstants/blob/master/json/xp_level.json

**Comment by sneakyimp1** [comment]
Pull request created.

**Comment by howardchung** [comment]
Thanks!
