### ISSUE TITLE
Data Features 

### ISSUE THREAD

**Issue by alexalperov** [odota/ui#939]
I am trying to do some predictive data analysis, but I can't find a dataset with all of the information I want. Some of the variables I haven't seen in a comprehensive data file, but would like to see:

Enemy Heroes
Allied Heroes
Any kind of chronology of item purchases
MMR
Win/Loss

Are these available in any single datadump? If not, do I have any options for parsing this data on my own?

**Comment by howardchung** [comment]
https://blog.opendota.com/2017/03/24/datadump2/

That'll have heroes, item logs for some matches, and win/loss.
