### ISSUE TITLE
Name of opponent team as table

### ISSUE THREAD

**Issue by neverperfect** [odota/ui#951]
Is there a query to add opponent (team) of which a team/player is playing against in the explorer?

**Comment by howardchung** [comment]
You mean as a filter or in the output table?

**Comment by neverperfect** [comment]
As an output table, so it shows up when saved as a CSV file

**Comment by howardchung** [comment]
You could do this with a query like:
https://www.opendota.com/explorer?sql=SELECT%0Amatches.match_id%2C%0Amatches.start_time%2C%0A((player_matches.player_slot%20%3C%20128)%20%3D%20matches.radiant_win)%20win%2C%0Aplayer_matches.hero_id%2C%0Aplayer_matches.account_id%2C%0Aleagues.name%20leaguename%2C%0Acase%20when%20(player_slot%20%3C%20128)%20then%20dire_team_id%20else%20radiant_team_id%20end%20opposing_team_id%0AFROM%20matches%0AJOIN%20match_patch%20using(match_id)%0AJOIN%20leagues%20using(leagueid)%0AJOIN%20player_matches%20using(match_id)%0ALEFT%20JOIN%20notable_players%20using(account_id)%0ALEFT%20JOIN%20teams%20using(team_id)%0AWHERE%20TRUE%0AAND%20player_matches.account_id%20%3D%20101495620%0AORDER%20BY%20matches.match_id%20DESC%20NULLS%20LAST%0ALIMIT%20200&format=

**Comment by neverperfect** [comment]
I tried using query attached below, with the intent of getting player's team he is playing at the time, not current team he is in.. But it gives me an error.
Help me please, thanks.
![image](https://cloud.githubusercontent.com/assets/10155244/26283356/21ae7952-3e51-11e7-9154-20db76128f77.png)

**Comment by howardchung** [comment]
Can you provide the query text or a link?

**Comment by neverperfect** [comment]
Here you go,
https://www.opendota.com/explorer?sql=select%20%0Aplayer_matches.account_id%2C%0Amatches.match_id%2C%0Amatches.start_time%2C%0A((player_matches.player_slot%20%3C%20128)%20%3D%20matches.radiant_win)%20win%2C%0Akills%2Cdeaths%2Cassists%2C%0Axp_per_min%2Cgold_per_min%2C%0Aplayer_matches.hero_id%2C%0Aleagues.name%20leaguename%2C%0Ateams.name%2C%0Acase%20when%20(player_slot%20%3C%20128)%20then%20dire_team_id%20else%20radiant_team_id%20end%20opposing_team_name%0Afrom%20matches%0Ajoin%20match_patch%20using%20(match_id)%0Ajoin%20leagues%20using%20(leagueid)%0Ajoin%20player_matches%20using(match_id)%0ALEFT%20JOIN%20notable_players%20using(account_id)%0Aleft%20join%20team_match%20using(match_id)%0AWHERE%20player_matches.account_id%20%3D%20111114687%0AAND%20team_match.radiant%20%3D%20(player_matches.player_slot%20%3C%20128)%0AAND%20matches.start_time%20%3E%3D%201437843600%0Aorder%20by%20match_id&format=table

**Comment by howardchung** [comment]
Try this:
https://www.opendota.com/explorer?sql=select%20%0Aplayer_matches.account_id%2C%0Amatches.match_id%2C%0Amatches.start_time%2C%0A((player_matches.player_slot%20%3C%20128)%20%3D%20matches.radiant_win)%20win%2C%0Akills%2Cdeaths%2Cassists%2C%0Axp_per_min%2Cgold_per_min%2C%0Aplayer_matches.hero_id%2C%0Aleagues.name%20leaguename%2C%0Ateams.name%20opposing_team%0Afrom%20matches%0Ajoin%20match_patch%20using%20(match_id)%0Ajoin%20leagues%20using%20(leagueid)%0Ajoin%20player_matches%20using(match_id)%0ALEFT%20JOIN%20notable_players%20using(account_id)%0Aleft%20join%20team_match%20using(match_id)%0Aleft%20join%20teams%20on%20case%20when%20(player_slot%20%3C%20128)%20then%20dire_team_id%20else%20radiant_team_id%20end%20%3D%20teams.team_id%0AWHERE%20player_matches.account_id%20%3D%20111114687%0AAND%20team_match.radiant%20%3D%20(player_matches.player_slot%20%3C%20128)%0AAND%20matches.start_time%20%3E%3D%201437843600%0Aorder%20by%20match_id&format=table

**Comment by neverperfect** [comment]
If I want to have y's team (as of match) next to the opposing_team id table, is it possible?

**Comment by howardchung** [comment]
Yes just add another column to the select and invert the logic for choosing the team to show.

**Comment by neverperfect** [comment]
I'm sorry, how do I do that?

**Comment by howardchung** [comment]
https://www.opendota.com/explorer?sql=select%20%0Aplayer_matches.account_id%2C%0Amatches.match_id%2C%0Amatches.start_time%2C%0A((player_matches.player_slot%20%3C%20128)%20%3D%20matches.radiant_win)%20win%2C%0Akills%2Cdeaths%2Cassists%2C%0Axp_per_min%2Cgold_per_min%2C%0Aplayer_matches.hero_id%2C%0Aleagues.name%20leaguename%2C%0Ateams.name%20opposing_team%2C%0At2.name%20team%0Afrom%20matches%0Ajoin%20match_patch%20using%20(match_id)%0Ajoin%20leagues%20using%20(leagueid)%0Ajoin%20player_matches%20using(match_id)%0ALEFT%20JOIN%20notable_players%20using(account_id)%0Aleft%20join%20team_match%20using(match_id)%0Aleft%20join%20teams%20on%20case%20when%20(player_slot%20%3C%20128)%20then%20dire_team_id%20else%20radiant_team_id%20end%20%3D%20teams.team_id%0Aleft%20join%20teams%20t2%20on%20case%20when%20(player_slot%20%3C%20128)%20then%20radiant_team_id%20else%20dire_team_id%20end%20%3D%20t2.team_id%0AWHERE%20player_matches.account_id%20%3D%20111114687%0AAND%20team_match.radiant%20%3D%20(player_matches.player_slot%20%3C%20128)%0AAND%20matches.start_time%20%3E%3D%201437843600%0Aorder%20by%20match_id&format=table
