### ISSUE TITLE
Show player trends averaged over last 20 games instead of computing global averages

### ISSUE THREAD

**Issue by vaibhav-y** [odota/ui#953]
I have opened a similar issue in odota/core as I was unsure which repository held logic for computing trends.

I recently began climbing ranked MMR and tried to use the trends page to gather some correlation between things I did in the last 20 games that may have lead to victory. My userpage (https://www.opendota.com/players/172152956/) shows point values for my averages, best, worst in the last 20 games, but my trends shows a global average trend which isn't as useful to visually infer things.

I suggest that trends be changed or there be a new tab added to show a moving average over the last 20 (or whatever number the user chooses) games. We can also add the best, and worst performances to this trends chart. I believe this will be a great addition since this actually helps users understand their performance trends and what they can work on for upcoming ranked games.

For example:
Here's my GPM trend based showing a global average. Note I've won the last 20 games with really high average GPM (~500) which isn't really evident here: https://www.opendota.com/players/172152956/trends/gold_per_min

I did a cursory search of the API but couldn't see an match specific GPM results in the API. Please let me know if there is one, I'd be happy to plot a chart contrasting the two approaches

**Comment by howardchung** [comment]
Closing as a duplicate, but I agree and think this would be a good change to make to trends.
