### ISSUE TITLE
WK reincarnation ult is reported as deaths on combat / story / teamfights

### ISSUE THREAD

**Issue by hfagard** [odota/ui#958]
For example in match 3179675740 I went 16-3-21. But in the combat log it shows 16-12, the 9 reincarnations should not be counted as deaths as a WK player knows dying has little consequences and does it on purpose in a fight. I think it would reflect my performance better if these reincarnations were not reports as death.

In the story (a feature which I love) it would be cool though to indicate if a WK has reincarnated. And also while you are at it, indicate if a played has reincarnated because he had the aegis.

**Comment by howardchung** [comment]
This is due to https://github.com/odota/core/issues/726 and doesn't have a fix yet.  The combat log doesn't indicate whether a unit died with WK ult/aegis.

**Comment by howardchung** [comment]
Closing as this is an upstream issue (but it's still a problem, this is just for avoiding duplicates)
