### ISSUE TITLE
Consider moving location of 'Logout' button

### ISSUE THREAD

**Issue by loganogden** [odota/ui#960]
This would be hugely appreciated from a UX standpoint. The user page and logout options are so close to one another that I find myself logging out unintentionally from time to time. Nesting it in the gear icon would be a nice, simple way to handle this. 

For as little as I imagine people use it the Logout button, it's too easy to hit by mistake.

**Comment by howardchung** [comment]
Sure, I think we can do this.

@mike-robertson @blukai for input

**Comment by Ricardo-Silva91** [comment]
Hello, i made a pull request with a proposed solution for this issue, #970 

If anything needs to be corrected/changed please advise.
