### ISSUE TITLE
hello i want to translate this website to chinese ,,but there is something wrong

### ISSUE THREAD

**Issue by xiaohangJose** [odota/ui#962]
just like this word 
HERO-PLAYER
I don't know where this word is.
I try to understand this word but there is no explain at https://translate.opendota.com/translate/yasp/6/en-zhcn  。。
so i can't translate until you provide these word's explation

**Comment by howardchung** [comment]
This is in the select menu at https://www.opendota.com/explorer

It refers to a hero-player combination (like AdmiralBulldog + Nature's Prophet)
