### ISSUE TITLE
Arc Warden's Tempest Double icon is outdated

### ISSUE THREAD

**Issue by Polygonalr** [odota/ui#967]
Applies when you look at any Arc Warden's skillbuild.
![untitled](https://cloud.githubusercontent.com/assets/16399656/26284630/a31afe9a-3e72-11e7-87c4-7daacbbaec52.png)

**Comment by howardchung** [comment]
What's wrong with it?  Looks like the same one as used here:
http://dota2.gamepedia.com/Arc_Warden

**Comment by howardchung** [comment]
Please reopen/comment if there are any further issues with this.
