### ISSUE TITLE
Allow input by player name for account_id inputs

### ISSUE THREAD

**Issue by howardchung** [odota/ui#97]
Allow search by player name (hit remote API) and resolve to account_ids.

This can utilize the peers data for a player.

Continuation of https://github.com/yasp-dota/yasp/issues/1119

**Comment by masad-frost** [comment]
What happens if 2 players have the same name?

I think a good enough solution to make this better is add peers as a datasource

**Comment by howardchung** [comment]
we could display the account id as well as the personaname for the search results.  The peers thing could work too.

**Comment by howardchung** [comment]
The peers one is probably easier to do, so we should probably start there.
