### ISSUE TITLE
Match analysis shouldn't count some items as unused

### ISSUE THREAD

**Issue by frozenspider** [odota/ui#974]
The following cases probably shouldn't be accounted as "unused items":
* Any item that was in inventory less than a minute, especially those purchased right before the game end
  * Example: https://www.opendota.com/matches/3208159551/analysis - I as Phoenix purchased Glimmer, disassembled it and sold immediately, but it was counted as 2 unused items
* Quelling blade
* RoB/Aquila (might be purchased for pushing purposes specifically)
* Linken's on cores? (a passive effect is usually enough)

**Comment by frozenspider** [comment]
Sorry, moved to `core` repo: https://github.com/odota/core/issues/1469

**Comment by howardchung** [comment]
Copying comment from @TheOriginalSoni:

Apart from that, there's a side issue of "If ironwood branches/buckler is used, that does not count as mekanasm usage", which seems to be the case right now.

Suggested pseudocode to solve a number of these issues - 

```
function numberofunuseditems():
	q={}
	for all items i:
		if (item i is purchased && game.endtiming - i.purchasetiming > 60)
		{
			maxcosti=i;
			for (all items i2 in itemgroup it of i)
			{
				if(i2 is purchased && i2.cost>maxcost && game.endtiming - i2.purchasetiming > 60)
				{
					maxcosti=i2;
				}
			}
			if(i2.used == false) q.push(i2);
		}
	return q.size();
```

This pseudocode always takes the highest cost item of a particular item_group (that the player has purchased), and considers that item's usage instead. Also all items that are bought less than a minute from the game end are ignored.

I think this should be good to solve most of these bugs

**Comment by JazzyJosh** [comment]
@howardchung I can look into this.

**Comment by howardchung** [comment]
Sure, sounds good!
