### ISSUE TITLE
"Wards placed" counter only counts when you placed your last ward

### ISSUE THREAD

**Issue by e314** [odota/ui#975]
On the "Vision" tab 

For example : https://www.opendota.com/matches/3209899070/vision
For both normal wards and sentries, the "Use" part of the chart is messed up.
Since smoke is often used from the courier, I can't tell if there's a problem with it aswell, and Dust counter seems to be fine

On the other hand, the log under is correct.

**Comment by howardchung** [comment]
@dartharaknus 

Yeah, I think we need to switching to counting the log for obs/sentry use because of the ward_dispenser item.

About smoke on couriers I'm not sure if it counts as the using player or the courier.
