### ISSUE TITLE
Failing to parse?

### ISSUE THREAD

**Issue by Prosta-piet** [odota/ui#977]
Not sure what is wrong, but despite logging in and checking on multiple systems, I can't get my games to parse...

![image](https://cloud.githubusercontent.com/assets/29040248/26547879/74b68ccc-4471-11e7-9acc-e857a3e8a71d.png)

Thanks for any assitance

**Comment by howardchung** [comment]
Need some additional information, like the match_id you're trying to parse?

**Comment by Prosta-piet** [comment]
Hey sorry,

It's all of my recent games, since I checked in again recently. My user
name is [CBK]Prosta-Piet, profile link
https://www.opendota.com/players/170339884,

Some of the match id's are 3208220419, 3208293690, 3204005993.

Thanks, cheers

**Comment by howardchung** [comment]
It looks like Valve's missing the replays for these matches:
http://replay214.valve.net/570/3208220419_490665718.dem.bz2
http://replay214.valve.net/570/3208293690_1353487025.dem.bz2
http://replay214.valve.net/570/3204005993_2100646515.dem.bz2

Unfortunately there's not a lot I can do about this.  I've seen some Reddit threads with people describing this issue, so hopefully Valve will fix it soon.
