### ISSUE TITLE
Suggestion: option to swap assists with deaths

### ISSUE THREAD

**Issue by weltensturm** [odota/ui#999]
IMO aligning deaths in the KDA bar to the right gives a better performance overview, and it's pretty easy to do with custom page CSS. But an option to swap the position of assists with deaths generally would be nice, as the numbers wouldn't be above the correct bar element anymore.

**Comment by howardchung** [comment]
I'm fine with it either way.  Anyone else have an opinion?

@blukai 
@dartharaknus

**Comment by blukai** [comment]
Agreed with u @howardchung. In dota 2 we always see K D A exactly in this sequence and it's good enough to not change it.

**Comment by dartharaknus** [comment]
We used the view from Dota2 in-game client. If Valve are using it as default, we should do default too.

**Comment by snugghash** [comment]
Pardon me, but why specifically do you want to not have options? We already have one UI, offering an option and picking a sane default among those seems better.

All I can think of is that options would force development around that behaviour, perhaps increasing bloating.

New dev here, will appreciate any insights around how this intuition is related development best practices.

**Comment by howardchung** [comment]
Having multiple options means testing is harder since we need to make sure any changes look OK with all combinations of options.  As you mentioned it also increases the amount of code.
